#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 11
#define STATE_COUNT 47
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 39
#define ALIAS_COUNT 1
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 16
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4

enum {
  anon_sym_ = 1,
  anon_sym_TAB = 2,
  anon_sym_2 = 3,
  anon_sym_3 = 4,
  aux_sym_field_token2 = 5,
  anon_sym_PIPE = 6,
  aux_sym__line_token1 = 7,
  sym__newline = 8,
  sym__blankline = 9,
  sym__overline = 10,
  sym__underline = 11,
  sym__char_bullet = 12,
  sym__numeric_bullet = 13,
  sym__text = 14,
  sym_emphasis = 15,
  sym_strong = 16,
  sym_interpreted_text = 17,
  sym_literal = 18,
  sym_substitution_reference = 19,
  sym__inline_target = 20,
  sym_footnote_reference = 21,
  sym_reference = 22,
  sym_standalone_hyperlink = 23,
  sym_document = 24,
  sym_section = 25,
  sym__body_elements = 26,
  sym_paragraph = 27,
  sym__list = 28,
  sym_bullet_list = 29,
  sym__bullet_list_item = 30,
  sym_enumerated_list = 31,
  sym__numeric_list_item = 32,
  aux_sym__line = 33,
  sym__inline_markup = 34,
  aux_sym_document_repeat1 = 35,
  aux_sym_paragraph_repeat1 = 36,
  aux_sym_bullet_list_repeat1 = 37,
  aux_sym_enumerated_list_repeat1 = 38,
  alias_sym_title = 39,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_] = " ",
  [anon_sym_TAB] = "\t",
  [anon_sym_2] = "",
  [anon_sym_3] = "\f",
  [aux_sym_field_token2] = "field_token2",
  [anon_sym_PIPE] = "|",
  [aux_sym__line_token1] = "_line_token1",
  [sym__newline] = "_newline",
  [sym__blankline] = "_blankline",
  [sym__overline] = "_overline",
  [sym__underline] = "_underline",
  [sym__char_bullet] = "_char_bullet",
  [sym__numeric_bullet] = "_numeric_bullet",
  [sym__text] = "_text",
  [sym_emphasis] = "emphasis",
  [sym_strong] = "strong",
  [sym_interpreted_text] = "interpreted_text",
  [sym_literal] = "literal",
  [sym_substitution_reference] = "substitution_reference",
  [sym__inline_target] = "target",
  [sym_footnote_reference] = "footnote_reference",
  [sym_reference] = "reference",
  [sym_standalone_hyperlink] = "standalone_hyperlink",
  [sym_document] = "document",
  [sym_section] = "section",
  [sym__body_elements] = "_body_elements",
  [sym_paragraph] = "paragraph",
  [sym__list] = "_list",
  [sym_bullet_list] = "bullet_list",
  [sym__bullet_list_item] = "list_item",
  [sym_enumerated_list] = "enumerated_list",
  [sym__numeric_list_item] = "list_item",
  [aux_sym__line] = "_line",
  [sym__inline_markup] = "_inline_markup",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_paragraph_repeat1] = "paragraph_repeat1",
  [aux_sym_bullet_list_repeat1] = "bullet_list_repeat1",
  [aux_sym_enumerated_list_repeat1] = "enumerated_list_repeat1",
  [alias_sym_title] = "title",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_] = anon_sym_,
  [anon_sym_TAB] = anon_sym_TAB,
  [anon_sym_2] = anon_sym_2,
  [anon_sym_3] = anon_sym_3,
  [aux_sym_field_token2] = aux_sym_field_token2,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [aux_sym__line_token1] = aux_sym__line_token1,
  [sym__newline] = sym__newline,
  [sym__blankline] = sym__blankline,
  [sym__overline] = sym__overline,
  [sym__underline] = sym__underline,
  [sym__char_bullet] = sym__char_bullet,
  [sym__numeric_bullet] = sym__numeric_bullet,
  [sym__text] = sym__text,
  [sym_emphasis] = sym_emphasis,
  [sym_strong] = sym_strong,
  [sym_interpreted_text] = sym_interpreted_text,
  [sym_literal] = sym_literal,
  [sym_substitution_reference] = sym_substitution_reference,
  [sym__inline_target] = sym__inline_target,
  [sym_footnote_reference] = sym_footnote_reference,
  [sym_reference] = sym_reference,
  [sym_standalone_hyperlink] = sym_standalone_hyperlink,
  [sym_document] = sym_document,
  [sym_section] = sym_section,
  [sym__body_elements] = sym__body_elements,
  [sym_paragraph] = sym_paragraph,
  [sym__list] = sym__list,
  [sym_bullet_list] = sym_bullet_list,
  [sym__bullet_list_item] = sym__bullet_list_item,
  [sym_enumerated_list] = sym_enumerated_list,
  [sym__numeric_list_item] = sym__bullet_list_item,
  [aux_sym__line] = aux_sym__line,
  [sym__inline_markup] = sym__inline_markup,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_paragraph_repeat1] = aux_sym_paragraph_repeat1,
  [aux_sym_bullet_list_repeat1] = aux_sym_bullet_list_repeat1,
  [aux_sym_enumerated_list_repeat1] = aux_sym_enumerated_list_repeat1,
  [alias_sym_title] = alias_sym_title,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TAB] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_3] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_field_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__line_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym__blankline] = {
    .visible = false,
    .named = true,
  },
  [sym__overline] = {
    .visible = false,
    .named = true,
  },
  [sym__underline] = {
    .visible = false,
    .named = true,
  },
  [sym__char_bullet] = {
    .visible = false,
    .named = true,
  },
  [sym__numeric_bullet] = {
    .visible = false,
    .named = true,
  },
  [sym__text] = {
    .visible = false,
    .named = true,
  },
  [sym_emphasis] = {
    .visible = true,
    .named = true,
  },
  [sym_strong] = {
    .visible = true,
    .named = true,
  },
  [sym_interpreted_text] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_substitution_reference] = {
    .visible = true,
    .named = true,
  },
  [sym__inline_target] = {
    .visible = true,
    .named = true,
  },
  [sym_footnote_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_standalone_hyperlink] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym__body_elements] = {
    .visible = false,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [sym__list] = {
    .visible = false,
    .named = true,
  },
  [sym_bullet_list] = {
    .visible = true,
    .named = true,
  },
  [sym__bullet_list_item] = {
    .visible = true,
    .named = true,
  },
  [sym_enumerated_list] = {
    .visible = true,
    .named = true,
  },
  [sym__numeric_list_item] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__line] = {
    .visible = false,
    .named = false,
  },
  [sym__inline_markup] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paragraph_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_bullet_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enumerated_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_title] = {
    .visible = true,
    .named = true,
  },
};

static TSSymbol ts_alias_sequences[3][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_title,
  },
  [2] = {
    [1] = alias_sym_title,
  },
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      if (lookahead == '\t') ADVANCE(4);
      if (lookahead == 11) ADVANCE(5);
      if (lookahead == '\f') ADVANCE(6);
      if (lookahead == ' ') ADVANCE(3);
      if (lookahead == '|') ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(7);
      END_STATE();
    case 1:
      if (lookahead == '\t') ADVANCE(4);
      if (lookahead == 11) ADVANCE(5);
      if (lookahead == '\f') ADVANCE(6);
      if (lookahead == ' ') ADVANCE(3);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_TAB);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_2);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_3);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(aux_sym_field_token2);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym__line_token1);
      if (lookahead == '\t' ||
          lookahead == 11 ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym__line_token1);
      if (eof) ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == 11 ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(9);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 10, .external_lex_state = 2},
  [2] = {.lex_state = 10, .external_lex_state = 2},
  [3] = {.lex_state = 10, .external_lex_state = 2},
  [4] = {.lex_state = 10, .external_lex_state = 2},
  [5] = {.lex_state = 10, .external_lex_state = 2},
  [6] = {.lex_state = 10, .external_lex_state = 2},
  [7] = {.lex_state = 10, .external_lex_state = 3},
  [8] = {.lex_state = 10, .external_lex_state = 4},
  [9] = {.lex_state = 10, .external_lex_state = 3},
  [10] = {.lex_state = 10, .external_lex_state = 3},
  [11] = {.lex_state = 10, .external_lex_state = 3},
  [12] = {.lex_state = 10, .external_lex_state = 4},
  [13] = {.lex_state = 10, .external_lex_state = 3},
  [14] = {.lex_state = 10, .external_lex_state = 4},
  [15] = {.lex_state = 10, .external_lex_state = 4},
  [16] = {.lex_state = 10, .external_lex_state = 4},
  [17] = {.lex_state = 10, .external_lex_state = 4},
  [18] = {.lex_state = 10, .external_lex_state = 4},
  [19] = {.lex_state = 10, .external_lex_state = 4},
  [20] = {.lex_state = 10, .external_lex_state = 4},
  [21] = {.lex_state = 10, .external_lex_state = 4},
  [22] = {.lex_state = 10, .external_lex_state = 4},
  [23] = {.lex_state = 10, .external_lex_state = 4},
  [24] = {.lex_state = 10, .external_lex_state = 5},
  [25] = {.lex_state = 10, .external_lex_state = 3},
  [26] = {.lex_state = 10, .external_lex_state = 4},
  [27] = {.lex_state = 10, .external_lex_state = 4},
  [28] = {.lex_state = 1, .external_lex_state = 6},
  [29] = {.lex_state = 1, .external_lex_state = 6},
  [30] = {.lex_state = 1, .external_lex_state = 6},
  [31] = {.lex_state = 1, .external_lex_state = 6},
  [32] = {.lex_state = 0, .external_lex_state = 7},
  [33] = {.lex_state = 0, .external_lex_state = 8},
  [34] = {.lex_state = 0, .external_lex_state = 7},
  [35] = {.lex_state = 0, .external_lex_state = 8},
  [36] = {.lex_state = 0, .external_lex_state = 9},
  [37] = {.lex_state = 0, .external_lex_state = 10},
  [38] = {.lex_state = 0, .external_lex_state = 9},
  [39] = {.lex_state = 0, .external_lex_state = 9},
  [40] = {.lex_state = 0, .external_lex_state = 9},
  [41] = {.lex_state = 0, .external_lex_state = 9},
  [42] = {.lex_state = 0, .external_lex_state = 6},
  [43] = {.lex_state = 0, .external_lex_state = 8},
  [44] = {.lex_state = 0, .external_lex_state = 7},
  [45] = {.lex_state = 0, .external_lex_state = 6},
  [46] = {.lex_state = 0, .external_lex_state = 6},
};

enum {
  ts_external_token__newline = 0,
  ts_external_token__blankline = 1,
  ts_external_token__overline = 2,
  ts_external_token__underline = 3,
  ts_external_token__char_bullet = 4,
  ts_external_token__numeric_bullet = 5,
  ts_external_token__text = 6,
  ts_external_token_emphasis = 7,
  ts_external_token_strong = 8,
  ts_external_token_interpreted_text = 9,
  ts_external_token_literal = 10,
  ts_external_token_substitution_reference = 11,
  ts_external_token__inline_target = 12,
  ts_external_token_footnote_reference = 13,
  ts_external_token_reference = 14,
  ts_external_token_standalone_hyperlink = 15,
};

static TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__newline] = sym__newline,
  [ts_external_token__blankline] = sym__blankline,
  [ts_external_token__overline] = sym__overline,
  [ts_external_token__underline] = sym__underline,
  [ts_external_token__char_bullet] = sym__char_bullet,
  [ts_external_token__numeric_bullet] = sym__numeric_bullet,
  [ts_external_token__text] = sym__text,
  [ts_external_token_emphasis] = sym_emphasis,
  [ts_external_token_strong] = sym_strong,
  [ts_external_token_interpreted_text] = sym_interpreted_text,
  [ts_external_token_literal] = sym_literal,
  [ts_external_token_substitution_reference] = sym_substitution_reference,
  [ts_external_token__inline_target] = sym__inline_target,
  [ts_external_token_footnote_reference] = sym_footnote_reference,
  [ts_external_token_reference] = sym_reference,
  [ts_external_token_standalone_hyperlink] = sym_standalone_hyperlink,
};

static bool ts_external_scanner_states[11][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__newline] = true,
    [ts_external_token__blankline] = true,
    [ts_external_token__overline] = true,
    [ts_external_token__underline] = true,
    [ts_external_token__char_bullet] = true,
    [ts_external_token__numeric_bullet] = true,
    [ts_external_token__text] = true,
    [ts_external_token_emphasis] = true,
    [ts_external_token_strong] = true,
    [ts_external_token_interpreted_text] = true,
    [ts_external_token_literal] = true,
    [ts_external_token_substitution_reference] = true,
    [ts_external_token__inline_target] = true,
    [ts_external_token_footnote_reference] = true,
    [ts_external_token_reference] = true,
    [ts_external_token_standalone_hyperlink] = true,
  },
  [2] = {
    [ts_external_token__newline] = true,
    [ts_external_token__blankline] = true,
    [ts_external_token__overline] = true,
    [ts_external_token__char_bullet] = true,
    [ts_external_token__numeric_bullet] = true,
    [ts_external_token__text] = true,
    [ts_external_token_emphasis] = true,
    [ts_external_token_strong] = true,
    [ts_external_token_interpreted_text] = true,
    [ts_external_token_literal] = true,
    [ts_external_token_substitution_reference] = true,
    [ts_external_token__inline_target] = true,
    [ts_external_token_footnote_reference] = true,
    [ts_external_token_reference] = true,
    [ts_external_token_standalone_hyperlink] = true,
  },
  [3] = {
    [ts_external_token__newline] = true,
    [ts_external_token__blankline] = true,
    [ts_external_token__text] = true,
    [ts_external_token_emphasis] = true,
    [ts_external_token_strong] = true,
    [ts_external_token_interpreted_text] = true,
    [ts_external_token_literal] = true,
    [ts_external_token_substitution_reference] = true,
    [ts_external_token__inline_target] = true,
    [ts_external_token_footnote_reference] = true,
    [ts_external_token_reference] = true,
    [ts_external_token_standalone_hyperlink] = true,
  },
  [4] = {
    [ts_external_token__newline] = true,
    [ts_external_token__text] = true,
    [ts_external_token_emphasis] = true,
    [ts_external_token_strong] = true,
    [ts_external_token_interpreted_text] = true,
    [ts_external_token_literal] = true,
    [ts_external_token_substitution_reference] = true,
    [ts_external_token__inline_target] = true,
    [ts_external_token_footnote_reference] = true,
    [ts_external_token_reference] = true,
    [ts_external_token_standalone_hyperlink] = true,
  },
  [5] = {
    [ts_external_token__newline] = true,
    [ts_external_token__underline] = true,
    [ts_external_token__text] = true,
    [ts_external_token_emphasis] = true,
    [ts_external_token_strong] = true,
    [ts_external_token_interpreted_text] = true,
    [ts_external_token_literal] = true,
    [ts_external_token_substitution_reference] = true,
    [ts_external_token__inline_target] = true,
    [ts_external_token_footnote_reference] = true,
    [ts_external_token_reference] = true,
    [ts_external_token_standalone_hyperlink] = true,
  },
  [6] = {
    [ts_external_token__newline] = true,
  },
  [7] = {
    [ts_external_token__newline] = true,
    [ts_external_token__char_bullet] = true,
  },
  [8] = {
    [ts_external_token__newline] = true,
    [ts_external_token__numeric_bullet] = true,
  },
  [9] = {
    [ts_external_token__newline] = true,
    [ts_external_token__blankline] = true,
  },
  [10] = {
    [ts_external_token__newline] = true,
    [ts_external_token__underline] = true,
  },
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_] = ACTIONS(1),
    [anon_sym_TAB] = ACTIONS(1),
    [anon_sym_2] = ACTIONS(1),
    [anon_sym_3] = ACTIONS(1),
    [aux_sym_field_token2] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym__newline] = ACTIONS(3),
    [sym__blankline] = ACTIONS(1),
    [sym__overline] = ACTIONS(1),
    [sym__underline] = ACTIONS(1),
    [sym__char_bullet] = ACTIONS(1),
    [sym__numeric_bullet] = ACTIONS(1),
    [sym__text] = ACTIONS(1),
    [sym_emphasis] = ACTIONS(1),
    [sym_strong] = ACTIONS(1),
    [sym_interpreted_text] = ACTIONS(1),
    [sym_literal] = ACTIONS(1),
    [sym_substitution_reference] = ACTIONS(1),
    [sym__inline_target] = ACTIONS(1),
    [sym_footnote_reference] = ACTIONS(1),
    [sym_reference] = ACTIONS(1),
    [sym_standalone_hyperlink] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(42),
    [sym_section] = STATE(2),
    [sym__body_elements] = STATE(2),
    [sym_paragraph] = STATE(40),
    [sym__list] = STATE(40),
    [sym_bullet_list] = STATE(40),
    [sym__bullet_list_item] = STATE(39),
    [sym_enumerated_list] = STATE(40),
    [sym__numeric_list_item] = STATE(38),
    [aux_sym__line] = STATE(11),
    [sym__inline_markup] = STATE(25),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_paragraph_repeat1] = STATE(12),
    [aux_sym_bullet_list_repeat1] = STATE(34),
    [aux_sym_enumerated_list_repeat1] = STATE(35),
    [ts_builtin_sym_end] = ACTIONS(5),
    [aux_sym__line_token1] = ACTIONS(7),
    [sym__newline] = ACTIONS(3),
    [sym__blankline] = ACTIONS(9),
    [sym__overline] = ACTIONS(11),
    [sym__char_bullet] = ACTIONS(13),
    [sym__numeric_bullet] = ACTIONS(15),
    [sym__text] = ACTIONS(7),
    [sym_emphasis] = ACTIONS(7),
    [sym_strong] = ACTIONS(7),
    [sym_interpreted_text] = ACTIONS(7),
    [sym_literal] = ACTIONS(7),
    [sym_substitution_reference] = ACTIONS(7),
    [sym__inline_target] = ACTIONS(7),
    [sym_footnote_reference] = ACTIONS(7),
    [sym_reference] = ACTIONS(7),
    [sym_standalone_hyperlink] = ACTIONS(7),
  },
  [2] = {
    [sym_section] = STATE(3),
    [sym__body_elements] = STATE(3),
    [sym_paragraph] = STATE(40),
    [sym__list] = STATE(40),
    [sym_bullet_list] = STATE(40),
    [sym__bullet_list_item] = STATE(39),
    [sym_enumerated_list] = STATE(40),
    [sym__numeric_list_item] = STATE(38),
    [aux_sym__line] = STATE(11),
    [sym__inline_markup] = STATE(25),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_paragraph_repeat1] = STATE(12),
    [aux_sym_bullet_list_repeat1] = STATE(34),
    [aux_sym_enumerated_list_repeat1] = STATE(35),
    [ts_builtin_sym_end] = ACTIONS(17),
    [aux_sym__line_token1] = ACTIONS(7),
    [sym__newline] = ACTIONS(3),
    [sym__blankline] = ACTIONS(19),
    [sym__overline] = ACTIONS(11),
    [sym__char_bullet] = ACTIONS(13),
    [sym__numeric_bullet] = ACTIONS(15),
    [sym__text] = ACTIONS(7),
    [sym_emphasis] = ACTIONS(7),
    [sym_strong] = ACTIONS(7),
    [sym_interpreted_text] = ACTIONS(7),
    [sym_literal] = ACTIONS(7),
    [sym_substitution_reference] = ACTIONS(7),
    [sym__inline_target] = ACTIONS(7),
    [sym_footnote_reference] = ACTIONS(7),
    [sym_reference] = ACTIONS(7),
    [sym_standalone_hyperlink] = ACTIONS(7),
  },
  [3] = {
    [sym_section] = STATE(3),
    [sym__body_elements] = STATE(3),
    [sym_paragraph] = STATE(40),
    [sym__list] = STATE(40),
    [sym_bullet_list] = STATE(40),
    [sym__bullet_list_item] = STATE(39),
    [sym_enumerated_list] = STATE(40),
    [sym__numeric_list_item] = STATE(38),
    [aux_sym__line] = STATE(11),
    [sym__inline_markup] = STATE(25),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_paragraph_repeat1] = STATE(12),
    [aux_sym_bullet_list_repeat1] = STATE(34),
    [aux_sym_enumerated_list_repeat1] = STATE(35),
    [ts_builtin_sym_end] = ACTIONS(21),
    [aux_sym__line_token1] = ACTIONS(23),
    [sym__newline] = ACTIONS(3),
    [sym__blankline] = ACTIONS(26),
    [sym__overline] = ACTIONS(29),
    [sym__char_bullet] = ACTIONS(32),
    [sym__numeric_bullet] = ACTIONS(35),
    [sym__text] = ACTIONS(23),
    [sym_emphasis] = ACTIONS(23),
    [sym_strong] = ACTIONS(23),
    [sym_interpreted_text] = ACTIONS(23),
    [sym_literal] = ACTIONS(23),
    [sym_substitution_reference] = ACTIONS(23),
    [sym__inline_target] = ACTIONS(23),
    [sym_footnote_reference] = ACTIONS(23),
    [sym_reference] = ACTIONS(23),
    [sym_standalone_hyperlink] = ACTIONS(23),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(38), 16,
      sym__blankline,
      sym__overline,
      sym__char_bullet,
      sym__numeric_bullet,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      ts_builtin_sym_end,
      aux_sym__line_token1,
  [22] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(40), 16,
      sym__blankline,
      sym__overline,
      sym__char_bullet,
      sym__numeric_bullet,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      ts_builtin_sym_end,
      aux_sym__line_token1,
  [44] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(42), 16,
      sym__blankline,
      sym__overline,
      sym__char_bullet,
      sym__numeric_bullet,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      ts_builtin_sym_end,
      aux_sym__line_token1,
  [66] = 5,
    ACTIONS(44), 1,
      sym__newline,
    ACTIONS(46), 1,
      sym__blankline,
    STATE(13), 1,
      aux_sym__line,
    STATE(25), 1,
      sym__inline_markup,
    ACTIONS(7), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [92] = 5,
    ACTIONS(3), 1,
      sym__newline,
    STATE(8), 1,
      aux_sym_paragraph_repeat1,
    STATE(14), 1,
      aux_sym__line,
    STATE(26), 1,
      sym__inline_markup,
    ACTIONS(48), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [118] = 4,
    STATE(13), 1,
      aux_sym__line,
    STATE(25), 1,
      sym__inline_markup,
    ACTIONS(51), 2,
      sym__newline,
      sym__blankline,
    ACTIONS(7), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [142] = 4,
    STATE(13), 1,
      aux_sym__line,
    STATE(25), 1,
      sym__inline_markup,
    ACTIONS(53), 2,
      sym__newline,
      sym__blankline,
    ACTIONS(7), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [166] = 5,
    ACTIONS(55), 1,
      sym__newline,
    ACTIONS(57), 1,
      sym__blankline,
    STATE(13), 1,
      aux_sym__line,
    STATE(25), 1,
      sym__inline_markup,
    ACTIONS(7), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [192] = 5,
    ACTIONS(3), 1,
      sym__newline,
    STATE(7), 1,
      aux_sym__line,
    STATE(8), 1,
      aux_sym_paragraph_repeat1,
    STATE(25), 1,
      sym__inline_markup,
    ACTIONS(7), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [218] = 4,
    STATE(13), 1,
      aux_sym__line,
    STATE(25), 1,
      sym__inline_markup,
    ACTIONS(62), 2,
      sym__newline,
      sym__blankline,
    ACTIONS(59), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [242] = 4,
    ACTIONS(44), 1,
      sym__newline,
    STATE(20), 1,
      aux_sym__line,
    STATE(26), 1,
      sym__inline_markup,
    ACTIONS(64), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [265] = 4,
    ACTIONS(3), 1,
      sym__newline,
    STATE(9), 1,
      aux_sym__line,
    STATE(25), 1,
      sym__inline_markup,
    ACTIONS(7), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [288] = 4,
    ACTIONS(66), 1,
      sym__newline,
    STATE(20), 1,
      aux_sym__line,
    STATE(26), 1,
      sym__inline_markup,
    ACTIONS(64), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [311] = 4,
    ACTIONS(3), 1,
      sym__newline,
    STATE(10), 1,
      aux_sym__line,
    STATE(25), 1,
      sym__inline_markup,
    ACTIONS(7), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [334] = 4,
    ACTIONS(51), 1,
      sym__newline,
    STATE(20), 1,
      aux_sym__line,
    STATE(26), 1,
      sym__inline_markup,
    ACTIONS(64), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [357] = 4,
    ACTIONS(53), 1,
      sym__newline,
    STATE(20), 1,
      aux_sym__line,
    STATE(26), 1,
      sym__inline_markup,
    ACTIONS(64), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [380] = 4,
    ACTIONS(62), 1,
      sym__newline,
    STATE(20), 1,
      aux_sym__line,
    STATE(26), 1,
      sym__inline_markup,
    ACTIONS(68), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [403] = 4,
    ACTIONS(3), 1,
      sym__newline,
    STATE(16), 1,
      aux_sym__line,
    STATE(26), 1,
      sym__inline_markup,
    ACTIONS(64), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [426] = 4,
    ACTIONS(3), 1,
      sym__newline,
    STATE(18), 1,
      aux_sym__line,
    STATE(26), 1,
      sym__inline_markup,
    ACTIONS(64), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [449] = 4,
    ACTIONS(3), 1,
      sym__newline,
    STATE(19), 1,
      aux_sym__line,
    STATE(26), 1,
      sym__inline_markup,
    ACTIONS(64), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [472] = 3,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(73), 1,
      sym__underline,
    ACTIONS(71), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [492] = 1,
    ACTIONS(75), 13,
      sym__newline,
      sym__blankline,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [508] = 1,
    ACTIONS(75), 12,
      sym__newline,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [523] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(71), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [540] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(77), 4,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_2,
      anon_sym_3,
  [550] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(79), 4,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_2,
      anon_sym_3,
  [560] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(81), 4,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_2,
      anon_sym_3,
  [570] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(83), 4,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_2,
      anon_sym_3,
  [580] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(85), 1,
      sym__char_bullet,
    STATE(32), 1,
      aux_sym_bullet_list_repeat1,
    STATE(45), 1,
      sym__bullet_list_item,
  [593] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(88), 1,
      sym__numeric_bullet,
    STATE(33), 1,
      aux_sym_enumerated_list_repeat1,
    STATE(46), 1,
      sym__numeric_list_item,
  [606] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(13), 1,
      sym__char_bullet,
    STATE(32), 1,
      aux_sym_bullet_list_repeat1,
    STATE(41), 1,
      sym__bullet_list_item,
  [619] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(15), 1,
      sym__numeric_bullet,
    STATE(33), 1,
      aux_sym_enumerated_list_repeat1,
    STATE(36), 1,
      sym__numeric_list_item,
  [632] = 2,
    ACTIONS(91), 1,
      sym__newline,
    ACTIONS(93), 1,
      sym__blankline,
  [639] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(95), 1,
      sym__underline,
  [646] = 2,
    ACTIONS(91), 1,
      sym__newline,
    ACTIONS(97), 1,
      sym__blankline,
  [653] = 2,
    ACTIONS(99), 1,
      sym__newline,
    ACTIONS(101), 1,
      sym__blankline,
  [660] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(103), 1,
      sym__blankline,
  [667] = 2,
    ACTIONS(99), 1,
      sym__newline,
    ACTIONS(105), 1,
      sym__blankline,
  [674] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(107), 1,
      ts_builtin_sym_end,
  [681] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(109), 1,
      sym__numeric_bullet,
  [688] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(111), 1,
      sym__char_bullet,
  [695] = 1,
    ACTIONS(99), 1,
      sym__newline,
  [699] = 1,
    ACTIONS(91), 1,
      sym__newline,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 22,
  [SMALL_STATE(6)] = 44,
  [SMALL_STATE(7)] = 66,
  [SMALL_STATE(8)] = 92,
  [SMALL_STATE(9)] = 118,
  [SMALL_STATE(10)] = 142,
  [SMALL_STATE(11)] = 166,
  [SMALL_STATE(12)] = 192,
  [SMALL_STATE(13)] = 218,
  [SMALL_STATE(14)] = 242,
  [SMALL_STATE(15)] = 265,
  [SMALL_STATE(16)] = 288,
  [SMALL_STATE(17)] = 311,
  [SMALL_STATE(18)] = 334,
  [SMALL_STATE(19)] = 357,
  [SMALL_STATE(20)] = 380,
  [SMALL_STATE(21)] = 403,
  [SMALL_STATE(22)] = 426,
  [SMALL_STATE(23)] = 449,
  [SMALL_STATE(24)] = 472,
  [SMALL_STATE(25)] = 492,
  [SMALL_STATE(26)] = 508,
  [SMALL_STATE(27)] = 523,
  [SMALL_STATE(28)] = 540,
  [SMALL_STATE(29)] = 550,
  [SMALL_STATE(30)] = 560,
  [SMALL_STATE(31)] = 570,
  [SMALL_STATE(32)] = 580,
  [SMALL_STATE(33)] = 593,
  [SMALL_STATE(34)] = 606,
  [SMALL_STATE(35)] = 619,
  [SMALL_STATE(36)] = 632,
  [SMALL_STATE(37)] = 639,
  [SMALL_STATE(38)] = 646,
  [SMALL_STATE(39)] = 653,
  [SMALL_STATE(40)] = 660,
  [SMALL_STATE(41)] = 667,
  [SMALL_STATE(42)] = 674,
  [SMALL_STATE(43)] = 681,
  [SMALL_STATE(44)] = 688,
  [SMALL_STATE(45)] = 695,
  [SMALL_STATE(46)] = 699,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(25),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(3),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(21),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(28),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(29),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 3, .production_id = 1),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__body_elements, 2),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 4, .production_id = 2),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 2),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(26),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__numeric_list_item, 3),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__bullet_list_item, 3),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 1),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__line, 2), SHIFT_REPEAT(25),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__line, 2),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__line, 2), SHIFT_REPEAT(26),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__line, 1),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bullet_list_repeat1, 2), SHIFT_REPEAT(30),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enumerated_list_repeat1, 2), SHIFT_REPEAT(31),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enumerated_list, 2),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enumerated_list, 1),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bullet_list, 1),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bullet_list, 2),
  [107] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enumerated_list_repeat1, 2),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_bullet_list_repeat1, 2),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_rst_external_scanner_create(void);
void tree_sitter_rst_external_scanner_destroy(void *);
bool tree_sitter_rst_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_rst_external_scanner_serialize(void *, char *);
void tree_sitter_rst_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_rst(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const unsigned short *)ts_parse_table,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .symbol_names = ts_symbol_names,
    .public_symbol_map = ts_symbol_map,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .external_scanner = {
      (const bool *)ts_external_scanner_states,
      ts_external_scanner_symbol_map,
      tree_sitter_rst_external_scanner_create,
      tree_sitter_rst_external_scanner_destroy,
      tree_sitter_rst_external_scanner_scan,
      tree_sitter_rst_external_scanner_serialize,
      tree_sitter_rst_external_scanner_deserialize,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
