#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 11
#define STATE_COUNT 115
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 68
#define ALIAS_COUNT 2
#define TOKEN_COUNT 36
#define EXTERNAL_TOKEN_COUNT 18
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4

enum {
  anon_sym_ = 1,
  anon_sym_TAB = 2,
  anon_sym_2 = 3,
  anon_sym_3 = 4,
  aux_sym_option_list_item_token1 = 5,
  anon_sym_PIPE = 6,
  aux_sym__single_line_block_token1 = 7,
  aux_sym_footnote_token1 = 8,
  aux_sym_citation_token1 = 9,
  aux_sym_target_token1 = 10,
  aux_sym_target_token2 = 11,
  anon_sym___ = 12,
  aux_sym_directive_token1 = 13,
  aux_sym_substitution_definition_token1 = 14,
  aux_sym__embed_directive_token1 = 15,
  anon_sym_COLON_COLON = 16,
  aux_sym__line_token1 = 17,
  sym__newline = 18,
  sym__blankline = 19,
  sym__overline = 20,
  sym__underline = 21,
  sym__char_bullet = 22,
  sym__numeric_bullet = 23,
  sym_field_name = 24,
  sym__text = 25,
  sym_emphasis = 26,
  sym_strong = 27,
  sym_interpreted_text = 28,
  sym_literal = 29,
  sym_substitution_reference = 30,
  sym__inline_target = 31,
  sym_footnote_reference = 32,
  sym_reference = 33,
  sym_standalone_hyperlink = 34,
  sym__explicit_markup_start = 35,
  sym_document = 36,
  sym_section = 37,
  sym__body_elements = 38,
  sym_paragraph = 39,
  sym__list = 40,
  sym_bullet_list = 41,
  sym__bullet_list_item = 42,
  sym_enumerated_list = 43,
  sym__numeric_list_item = 44,
  sym_field_list = 45,
  sym_field = 46,
  sym_option_list = 47,
  sym_option_list_item = 48,
  sym__explicit_markup_block = 49,
  sym__markup_block = 50,
  sym_footnote = 51,
  sym_citation = 52,
  sym_target = 53,
  sym__anonymous_target = 54,
  sym_directive = 55,
  sym_substitution_definition = 56,
  sym__embed_directive = 57,
  sym_comment = 58,
  aux_sym__line = 59,
  sym__inline_markup = 60,
  aux_sym_document_repeat1 = 61,
  aux_sym_paragraph_repeat1 = 62,
  aux_sym_bullet_list_repeat1 = 63,
  aux_sym_enumerated_list_repeat1 = 64,
  aux_sym_field_list_repeat1 = 65,
  aux_sym_option_list_repeat1 = 66,
  aux_sym__explicit_markup_block_repeat1 = 67,
  alias_sym_field_body = 68,
  alias_sym_title = 69,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_] = " ",
  [anon_sym_TAB] = "\t",
  [anon_sym_2] = "",
  [anon_sym_3] = "\f",
  [aux_sym_option_list_item_token1] = "option_list_item_token1",
  [anon_sym_PIPE] = "|",
  [aux_sym__single_line_block_token1] = "_single_line_block_token1",
  [aux_sym_footnote_token1] = "footnote_token1",
  [aux_sym_citation_token1] = "citation_token1",
  [aux_sym_target_token1] = "target_token1",
  [aux_sym_target_token2] = "target_token2",
  [anon_sym___] = "__",
  [aux_sym_directive_token1] = "directive_token1",
  [aux_sym_substitution_definition_token1] = "substitution_definition_token1",
  [aux_sym__embed_directive_token1] = "_embed_directive_token1",
  [anon_sym_COLON_COLON] = "::",
  [aux_sym__line_token1] = "_line_token1",
  [sym__newline] = "_newline",
  [sym__blankline] = "_blankline",
  [sym__overline] = "_overline",
  [sym__underline] = "_underline",
  [sym__char_bullet] = "_char_bullet",
  [sym__numeric_bullet] = "_numeric_bullet",
  [sym_field_name] = "field_name",
  [sym__text] = "_text",
  [sym_emphasis] = "emphasis",
  [sym_strong] = "strong",
  [sym_interpreted_text] = "interpreted_text",
  [sym_literal] = "literal",
  [sym_substitution_reference] = "substitution_reference",
  [sym__inline_target] = "target",
  [sym_footnote_reference] = "footnote_reference",
  [sym_reference] = "reference",
  [sym_standalone_hyperlink] = "standalone_hyperlink",
  [sym__explicit_markup_start] = "_explicit_markup_start",
  [sym_document] = "document",
  [sym_section] = "section",
  [sym__body_elements] = "_body_elements",
  [sym_paragraph] = "paragraph",
  [sym__list] = "_list",
  [sym_bullet_list] = "bullet_list",
  [sym__bullet_list_item] = "list_item",
  [sym_enumerated_list] = "enumerated_list",
  [sym__numeric_list_item] = "list_item",
  [sym_field_list] = "field_list",
  [sym_field] = "field",
  [sym_option_list] = "option_list",
  [sym_option_list_item] = "option_list_item",
  [sym__explicit_markup_block] = "_explicit_markup_block",
  [sym__markup_block] = "_markup_block",
  [sym_footnote] = "footnote",
  [sym_citation] = "citation",
  [sym_target] = "target",
  [sym__anonymous_target] = "target",
  [sym_directive] = "directive",
  [sym_substitution_definition] = "substitution_definition",
  [sym__embed_directive] = "_embed_directive",
  [sym_comment] = "comment",
  [aux_sym__line] = "_line",
  [sym__inline_markup] = "_inline_markup",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_paragraph_repeat1] = "paragraph_repeat1",
  [aux_sym_bullet_list_repeat1] = "bullet_list_repeat1",
  [aux_sym_enumerated_list_repeat1] = "enumerated_list_repeat1",
  [aux_sym_field_list_repeat1] = "field_list_repeat1",
  [aux_sym_option_list_repeat1] = "option_list_repeat1",
  [aux_sym__explicit_markup_block_repeat1] = "_explicit_markup_block_repeat1",
  [alias_sym_field_body] = "field_body",
  [alias_sym_title] = "title",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_] = anon_sym_,
  [anon_sym_TAB] = anon_sym_TAB,
  [anon_sym_2] = anon_sym_2,
  [anon_sym_3] = anon_sym_3,
  [aux_sym_option_list_item_token1] = aux_sym_option_list_item_token1,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [aux_sym__single_line_block_token1] = aux_sym__single_line_block_token1,
  [aux_sym_footnote_token1] = aux_sym_footnote_token1,
  [aux_sym_citation_token1] = aux_sym_citation_token1,
  [aux_sym_target_token1] = aux_sym_target_token1,
  [aux_sym_target_token2] = aux_sym_target_token2,
  [anon_sym___] = anon_sym___,
  [aux_sym_directive_token1] = aux_sym_directive_token1,
  [aux_sym_substitution_definition_token1] = aux_sym_substitution_definition_token1,
  [aux_sym__embed_directive_token1] = aux_sym__embed_directive_token1,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [aux_sym__line_token1] = aux_sym__line_token1,
  [sym__newline] = sym__newline,
  [sym__blankline] = sym__blankline,
  [sym__overline] = sym__overline,
  [sym__underline] = sym__underline,
  [sym__char_bullet] = sym__char_bullet,
  [sym__numeric_bullet] = sym__numeric_bullet,
  [sym_field_name] = sym_field_name,
  [sym__text] = sym__text,
  [sym_emphasis] = sym_emphasis,
  [sym_strong] = sym_strong,
  [sym_interpreted_text] = sym_interpreted_text,
  [sym_literal] = sym_literal,
  [sym_substitution_reference] = sym_substitution_reference,
  [sym__inline_target] = sym_target,
  [sym_footnote_reference] = sym_footnote_reference,
  [sym_reference] = sym_reference,
  [sym_standalone_hyperlink] = sym_standalone_hyperlink,
  [sym__explicit_markup_start] = sym__explicit_markup_start,
  [sym_document] = sym_document,
  [sym_section] = sym_section,
  [sym__body_elements] = sym__body_elements,
  [sym_paragraph] = sym_paragraph,
  [sym__list] = sym__list,
  [sym_bullet_list] = sym_bullet_list,
  [sym__bullet_list_item] = sym__bullet_list_item,
  [sym_enumerated_list] = sym_enumerated_list,
  [sym__numeric_list_item] = sym__bullet_list_item,
  [sym_field_list] = sym_field_list,
  [sym_field] = sym_field,
  [sym_option_list] = sym_option_list,
  [sym_option_list_item] = sym_option_list_item,
  [sym__explicit_markup_block] = sym__explicit_markup_block,
  [sym__markup_block] = sym__markup_block,
  [sym_footnote] = sym_footnote,
  [sym_citation] = sym_citation,
  [sym_target] = sym_target,
  [sym__anonymous_target] = sym_target,
  [sym_directive] = sym_directive,
  [sym_substitution_definition] = sym_substitution_definition,
  [sym__embed_directive] = sym__embed_directive,
  [sym_comment] = sym_comment,
  [aux_sym__line] = aux_sym__line,
  [sym__inline_markup] = sym__inline_markup,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_paragraph_repeat1] = aux_sym_paragraph_repeat1,
  [aux_sym_bullet_list_repeat1] = aux_sym_bullet_list_repeat1,
  [aux_sym_enumerated_list_repeat1] = aux_sym_enumerated_list_repeat1,
  [aux_sym_field_list_repeat1] = aux_sym_field_list_repeat1,
  [aux_sym_option_list_repeat1] = aux_sym_option_list_repeat1,
  [aux_sym__explicit_markup_block_repeat1] = aux_sym__explicit_markup_block_repeat1,
  [alias_sym_field_body] = alias_sym_field_body,
  [alias_sym_title] = alias_sym_title,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TAB] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_3] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_option_list_item_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__single_line_block_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_footnote_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_citation_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_target_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_target_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym___] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_directive_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_substitution_definition_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__embed_directive_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__line_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym__blankline] = {
    .visible = false,
    .named = true,
  },
  [sym__overline] = {
    .visible = false,
    .named = true,
  },
  [sym__underline] = {
    .visible = false,
    .named = true,
  },
  [sym__char_bullet] = {
    .visible = false,
    .named = true,
  },
  [sym__numeric_bullet] = {
    .visible = false,
    .named = true,
  },
  [sym_field_name] = {
    .visible = true,
    .named = true,
  },
  [sym__text] = {
    .visible = false,
    .named = true,
  },
  [sym_emphasis] = {
    .visible = true,
    .named = true,
  },
  [sym_strong] = {
    .visible = true,
    .named = true,
  },
  [sym_interpreted_text] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_substitution_reference] = {
    .visible = true,
    .named = true,
  },
  [sym__inline_target] = {
    .visible = true,
    .named = true,
  },
  [sym_footnote_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_standalone_hyperlink] = {
    .visible = true,
    .named = true,
  },
  [sym__explicit_markup_start] = {
    .visible = false,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym__body_elements] = {
    .visible = false,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [sym__list] = {
    .visible = false,
    .named = true,
  },
  [sym_bullet_list] = {
    .visible = true,
    .named = true,
  },
  [sym__bullet_list_item] = {
    .visible = true,
    .named = true,
  },
  [sym_enumerated_list] = {
    .visible = true,
    .named = true,
  },
  [sym__numeric_list_item] = {
    .visible = true,
    .named = true,
  },
  [sym_field_list] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_option_list] = {
    .visible = true,
    .named = true,
  },
  [sym_option_list_item] = {
    .visible = true,
    .named = true,
  },
  [sym__explicit_markup_block] = {
    .visible = false,
    .named = true,
  },
  [sym__markup_block] = {
    .visible = false,
    .named = true,
  },
  [sym_footnote] = {
    .visible = true,
    .named = true,
  },
  [sym_citation] = {
    .visible = true,
    .named = true,
  },
  [sym_target] = {
    .visible = true,
    .named = true,
  },
  [sym__anonymous_target] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_substitution_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__embed_directive] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__line] = {
    .visible = false,
    .named = false,
  },
  [sym__inline_markup] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paragraph_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_bullet_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enumerated_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_field_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_option_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__explicit_markup_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_field_body] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_title] = {
    .visible = true,
    .named = true,
  },
};

static TSSymbol ts_alias_sequences[4][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [2] = alias_sym_field_body,
  },
  [2] = {
    [0] = alias_sym_title,
  },
  [3] = {
    [1] = alias_sym_title,
  },
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(42);
      if (lookahead == '\t') ADVANCE(44);
      if (lookahead == 11) ADVANCE(45);
      if (lookahead == '\f') ADVANCE(46);
      if (lookahead == ' ') ADVANCE(43);
      if (lookahead == '+') ADVANCE(38);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == '/') ADVANCE(38);
      if (lookahead == ':') ADVANCE(5);
      if (lookahead == '_') ADVANCE(19);
      if (lookahead == '|') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(3);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == '*') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 3:
      if (lookahead == '+') ADVANCE(38);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == '/') ADVANCE(38);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 5:
      if (lookahead == ':') ADVANCE(60);
      END_STATE();
    case 6:
      if (lookahead == ':') ADVANCE(52);
      END_STATE();
    case 7:
      if (lookahead == ':') ADVANCE(52);
      if (lookahead == '_') ADVANCE(20);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == ':') ADVANCE(52);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 9:
      if (lookahead == ':') ADVANCE(53);
      if (lookahead == '_') ADVANCE(12);
      if (lookahead == '`') ADVANCE(7);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == ':') ADVANCE(53);
      if (lookahead == '`') ADVANCE(20);
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 11:
      if (lookahead == ':') ADVANCE(56);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          lookahead == '_') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 12:
      if (lookahead == ':') ADVANCE(22);
      if (lookahead == '_') ADVANCE(12);
      if (lookahead == '`') ADVANCE(7);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 13:
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          lookahead == '_') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 14:
      if (lookahead == ']') ADVANCE(33);
      END_STATE();
    case 15:
      if (lookahead == ']') ADVANCE(33);
      if (lookahead == '-' ||
          lookahead == '.' ||
          lookahead == '_') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 16:
      if (lookahead == ']') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 17:
      if (lookahead == ']') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 18:
      if (lookahead == ']') ADVANCE(34);
      if (lookahead == '-' ||
          lookahead == '.' ||
          lookahead == '_') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      if (lookahead == '_') ADVANCE(55);
      END_STATE();
    case 20:
      if (lookahead == '_') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(7);
      END_STATE();
    case 21:
      if (lookahead == '_') ADVANCE(6);
      if (lookahead == '`') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(8);
      END_STATE();
    case 22:
      if (lookahead == '`') ADVANCE(6);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 23:
      if (lookahead == '|') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(28);
      END_STATE();
    case 24:
      if (lookahead == '|') ADVANCE(25);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(24);
      END_STATE();
    case 25:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(58);
      if (lookahead == 11 ||
          lookahead == '\f') ADVANCE(57);
      if (lookahead == '\r') ADVANCE(28);
      if (lookahead == '|') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(24);
      END_STATE();
    case 26:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(58);
      if (lookahead == 11 ||
          lookahead == '\f') ADVANCE(57);
      if (lookahead == '\r') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(24);
      END_STATE();
    case 27:
      if (lookahead == '\t' ||
          lookahead == 11 ||
          lookahead == '\f') ADVANCE(31);
      if (lookahead == ' ') ADVANCE(32);
      if (lookahead == ',') ADVANCE(1);
      if (lookahead == '=') ADVANCE(39);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 28:
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(24);
      END_STATE();
    case 29:
      if (lookahead == '-' ||
          lookahead == '.' ||
          lookahead == '_') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 30:
      if (lookahead == '\t' ||
          lookahead == 11 ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead == ',') ADVANCE(1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 31:
      if (lookahead == '\t' ||
          lookahead == 11 ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(47);
      END_STATE();
    case 32:
      if (lookahead == '\t' ||
          lookahead == 11 ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 33:
      if (lookahead == '\t' ||
          lookahead == 11 ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(50);
      END_STATE();
    case 34:
      if (lookahead == '\t' ||
          lookahead == 11 ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(51);
      END_STATE();
    case 35:
      if (lookahead == '\t' ||
          lookahead == 11 ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(40);
      END_STATE();
    case 36:
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          lookahead == ':' ||
          lookahead == '_') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 37:
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          lookahead == ':' ||
          lookahead == '_') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 38:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 39:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 40:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(54);
      END_STATE();
    case 41:
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ') ADVANCE(23);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_);
      if (lookahead == '[') ADVANCE(2);
      if (lookahead == '_') ADVANCE(21);
      if (lookahead == '|') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_TAB);
      if (lookahead == '[') ADVANCE(2);
      if (lookahead == '_') ADVANCE(21);
      if (lookahead == '|') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_2);
      if (lookahead == '[') ADVANCE(2);
      if (lookahead == '_') ADVANCE(21);
      if (lookahead == '|') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_3);
      if (lookahead == '[') ADVANCE(2);
      if (lookahead == '_') ADVANCE(21);
      if (lookahead == '|') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_option_list_item_token1);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '\t' ||
          lookahead == 11 ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(49);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym__single_line_block_token1);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_footnote_token1);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_citation_token1);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_target_token1);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_target_token1);
      if (lookahead == '`') ADVANCE(6);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_target_token2);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym___);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_directive_token1);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          lookahead == ':' ||
          lookahead == '_') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_substitution_definition_token1);
      if (lookahead == '|') ADVANCE(25);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(24);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_substitution_definition_token1);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(24);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym__embed_directive_token1);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          lookahead == ':' ||
          lookahead == '_') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym__line_token1);
      if (lookahead == '\t' ||
          lookahead == 11 ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym__line_token1);
      if (eof) ADVANCE(42);
      if (lookahead == '\t' ||
          lookahead == 11 ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(61);
      if (lookahead == '+') ADVANCE(38);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == '/') ADVANCE(38);
      if (lookahead == '_') ADVANCE(19);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 62, .external_lex_state = 2},
  [2] = {.lex_state = 62, .external_lex_state = 2},
  [3] = {.lex_state = 62, .external_lex_state = 2},
  [4] = {.lex_state = 62, .external_lex_state = 2},
  [5] = {.lex_state = 62, .external_lex_state = 2},
  [6] = {.lex_state = 62, .external_lex_state = 2},
  [7] = {.lex_state = 62, .external_lex_state = 3},
  [8] = {.lex_state = 62, .external_lex_state = 4},
  [9] = {.lex_state = 62, .external_lex_state = 3},
  [10] = {.lex_state = 62, .external_lex_state = 3},
  [11] = {.lex_state = 62, .external_lex_state = 3},
  [12] = {.lex_state = 62, .external_lex_state = 3},
  [13] = {.lex_state = 62, .external_lex_state = 3},
  [14] = {.lex_state = 62, .external_lex_state = 3},
  [15] = {.lex_state = 62, .external_lex_state = 3},
  [16] = {.lex_state = 62, .external_lex_state = 3},
  [17] = {.lex_state = 62, .external_lex_state = 3},
  [18] = {.lex_state = 62, .external_lex_state = 3},
  [19] = {.lex_state = 62, .external_lex_state = 4},
  [20] = {.lex_state = 62, .external_lex_state = 3},
  [21] = {.lex_state = 62, .external_lex_state = 4},
  [22] = {.lex_state = 62, .external_lex_state = 4},
  [23] = {.lex_state = 62, .external_lex_state = 4},
  [24] = {.lex_state = 62, .external_lex_state = 4},
  [25] = {.lex_state = 62, .external_lex_state = 4},
  [26] = {.lex_state = 62, .external_lex_state = 4},
  [27] = {.lex_state = 62, .external_lex_state = 4},
  [28] = {.lex_state = 62, .external_lex_state = 4},
  [29] = {.lex_state = 62, .external_lex_state = 4},
  [30] = {.lex_state = 62, .external_lex_state = 4},
  [31] = {.lex_state = 62, .external_lex_state = 4},
  [32] = {.lex_state = 62, .external_lex_state = 4},
  [33] = {.lex_state = 62, .external_lex_state = 4},
  [34] = {.lex_state = 62, .external_lex_state = 4},
  [35] = {.lex_state = 62, .external_lex_state = 4},
  [36] = {.lex_state = 62, .external_lex_state = 4},
  [37] = {.lex_state = 62, .external_lex_state = 4},
  [38] = {.lex_state = 62, .external_lex_state = 4},
  [39] = {.lex_state = 62, .external_lex_state = 4},
  [40] = {.lex_state = 62, .external_lex_state = 4},
  [41] = {.lex_state = 62, .external_lex_state = 4},
  [42] = {.lex_state = 62, .external_lex_state = 4},
  [43] = {.lex_state = 62, .external_lex_state = 4},
  [44] = {.lex_state = 62, .external_lex_state = 4},
  [45] = {.lex_state = 62, .external_lex_state = 4},
  [46] = {.lex_state = 62, .external_lex_state = 4},
  [47] = {.lex_state = 62, .external_lex_state = 4},
  [48] = {.lex_state = 62, .external_lex_state = 4},
  [49] = {.lex_state = 62, .external_lex_state = 4},
  [50] = {.lex_state = 62, .external_lex_state = 4},
  [51] = {.lex_state = 62, .external_lex_state = 4},
  [52] = {.lex_state = 62, .external_lex_state = 3},
  [53] = {.lex_state = 62, .external_lex_state = 5},
  [54] = {.lex_state = 62, .external_lex_state = 4},
  [55] = {.lex_state = 0, .external_lex_state = 6},
  [56] = {.lex_state = 0, .external_lex_state = 6},
  [57] = {.lex_state = 62, .external_lex_state = 4},
  [58] = {.lex_state = 0, .external_lex_state = 7},
  [59] = {.lex_state = 0, .external_lex_state = 8},
  [60] = {.lex_state = 0, .external_lex_state = 7},
  [61] = {.lex_state = 0, .external_lex_state = 8},
  [62] = {.lex_state = 0, .external_lex_state = 8},
  [63] = {.lex_state = 0, .external_lex_state = 8},
  [64] = {.lex_state = 0, .external_lex_state = 8},
  [65] = {.lex_state = 0, .external_lex_state = 8},
  [66] = {.lex_state = 0, .external_lex_state = 8},
  [67] = {.lex_state = 0, .external_lex_state = 8},
  [68] = {.lex_state = 0, .external_lex_state = 8},
  [69] = {.lex_state = 0, .external_lex_state = 8},
  [70] = {.lex_state = 0, .external_lex_state = 9},
  [71] = {.lex_state = 0, .external_lex_state = 10},
  [72] = {.lex_state = 0, .external_lex_state = 10},
  [73] = {.lex_state = 0, .external_lex_state = 11},
  [74] = {.lex_state = 0, .external_lex_state = 9},
  [75] = {.lex_state = 0, .external_lex_state = 11},
  [76] = {.lex_state = 0, .external_lex_state = 8},
  [77] = {.lex_state = 0, .external_lex_state = 8},
  [78] = {.lex_state = 0, .external_lex_state = 8},
  [79] = {.lex_state = 35, .external_lex_state = 7},
  [80] = {.lex_state = 0, .external_lex_state = 8},
  [81] = {.lex_state = 35, .external_lex_state = 7},
  [82] = {.lex_state = 0, .external_lex_state = 6},
  [83] = {.lex_state = 0, .external_lex_state = 7},
  [84] = {.lex_state = 0, .external_lex_state = 7},
  [85] = {.lex_state = 0, .external_lex_state = 7},
  [86] = {.lex_state = 35, .external_lex_state = 8},
  [87] = {.lex_state = 0, .external_lex_state = 7},
  [88] = {.lex_state = 0, .external_lex_state = 8},
  [89] = {.lex_state = 0, .external_lex_state = 12},
  [90] = {.lex_state = 0, .external_lex_state = 9},
  [91] = {.lex_state = 0, .external_lex_state = 10},
  [92] = {.lex_state = 0, .external_lex_state = 7},
  [93] = {.lex_state = 35, .external_lex_state = 8},
  [94] = {.lex_state = 0, .external_lex_state = 7},
  [95] = {.lex_state = 0, .external_lex_state = 7},
  [96] = {.lex_state = 0, .external_lex_state = 7},
  [97] = {.lex_state = 0, .external_lex_state = 7},
  [98] = {.lex_state = 0, .external_lex_state = 7},
  [99] = {.lex_state = 0, .external_lex_state = 7},
  [100] = {.lex_state = 0, .external_lex_state = 7},
  [101] = {.lex_state = 0, .external_lex_state = 7},
  [102] = {.lex_state = 0, .external_lex_state = 8},
  [103] = {.lex_state = 0, .external_lex_state = 11},
  [104] = {.lex_state = 0, .external_lex_state = 8},
  [105] = {.lex_state = 0, .external_lex_state = 8},
  [106] = {.lex_state = 0, .external_lex_state = 7},
  [107] = {.lex_state = 0, .external_lex_state = 8},
  [108] = {.lex_state = 0, .external_lex_state = 8},
  [109] = {.lex_state = 0, .external_lex_state = 8},
  [110] = {.lex_state = 0, .external_lex_state = 8},
  [111] = {.lex_state = 0, .external_lex_state = 8},
  [112] = {.lex_state = 0, .external_lex_state = 8},
  [113] = {.lex_state = 0, .external_lex_state = 8},
  [114] = {.lex_state = 0, .external_lex_state = 8},
};

enum {
  ts_external_token__newline = 0,
  ts_external_token__blankline = 1,
  ts_external_token__overline = 2,
  ts_external_token__underline = 3,
  ts_external_token__char_bullet = 4,
  ts_external_token__numeric_bullet = 5,
  ts_external_token_field_name = 6,
  ts_external_token__text = 7,
  ts_external_token_emphasis = 8,
  ts_external_token_strong = 9,
  ts_external_token_interpreted_text = 10,
  ts_external_token_literal = 11,
  ts_external_token_substitution_reference = 12,
  ts_external_token__inline_target = 13,
  ts_external_token_footnote_reference = 14,
  ts_external_token_reference = 15,
  ts_external_token_standalone_hyperlink = 16,
  ts_external_token__explicit_markup_start = 17,
};

static TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__newline] = sym__newline,
  [ts_external_token__blankline] = sym__blankline,
  [ts_external_token__overline] = sym__overline,
  [ts_external_token__underline] = sym__underline,
  [ts_external_token__char_bullet] = sym__char_bullet,
  [ts_external_token__numeric_bullet] = sym__numeric_bullet,
  [ts_external_token_field_name] = sym_field_name,
  [ts_external_token__text] = sym__text,
  [ts_external_token_emphasis] = sym_emphasis,
  [ts_external_token_strong] = sym_strong,
  [ts_external_token_interpreted_text] = sym_interpreted_text,
  [ts_external_token_literal] = sym_literal,
  [ts_external_token_substitution_reference] = sym_substitution_reference,
  [ts_external_token__inline_target] = sym__inline_target,
  [ts_external_token_footnote_reference] = sym_footnote_reference,
  [ts_external_token_reference] = sym_reference,
  [ts_external_token_standalone_hyperlink] = sym_standalone_hyperlink,
  [ts_external_token__explicit_markup_start] = sym__explicit_markup_start,
};

static bool ts_external_scanner_states[13][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__newline] = true,
    [ts_external_token__blankline] = true,
    [ts_external_token__overline] = true,
    [ts_external_token__underline] = true,
    [ts_external_token__char_bullet] = true,
    [ts_external_token__numeric_bullet] = true,
    [ts_external_token_field_name] = true,
    [ts_external_token__text] = true,
    [ts_external_token_emphasis] = true,
    [ts_external_token_strong] = true,
    [ts_external_token_interpreted_text] = true,
    [ts_external_token_literal] = true,
    [ts_external_token_substitution_reference] = true,
    [ts_external_token__inline_target] = true,
    [ts_external_token_footnote_reference] = true,
    [ts_external_token_reference] = true,
    [ts_external_token_standalone_hyperlink] = true,
    [ts_external_token__explicit_markup_start] = true,
  },
  [2] = {
    [ts_external_token__newline] = true,
    [ts_external_token__blankline] = true,
    [ts_external_token__overline] = true,
    [ts_external_token__char_bullet] = true,
    [ts_external_token__numeric_bullet] = true,
    [ts_external_token_field_name] = true,
    [ts_external_token__text] = true,
    [ts_external_token_emphasis] = true,
    [ts_external_token_strong] = true,
    [ts_external_token_interpreted_text] = true,
    [ts_external_token_literal] = true,
    [ts_external_token_substitution_reference] = true,
    [ts_external_token__inline_target] = true,
    [ts_external_token_footnote_reference] = true,
    [ts_external_token_reference] = true,
    [ts_external_token_standalone_hyperlink] = true,
    [ts_external_token__explicit_markup_start] = true,
  },
  [3] = {
    [ts_external_token__newline] = true,
    [ts_external_token__blankline] = true,
    [ts_external_token__text] = true,
    [ts_external_token_emphasis] = true,
    [ts_external_token_strong] = true,
    [ts_external_token_interpreted_text] = true,
    [ts_external_token_literal] = true,
    [ts_external_token_substitution_reference] = true,
    [ts_external_token__inline_target] = true,
    [ts_external_token_footnote_reference] = true,
    [ts_external_token_reference] = true,
    [ts_external_token_standalone_hyperlink] = true,
  },
  [4] = {
    [ts_external_token__newline] = true,
    [ts_external_token__text] = true,
    [ts_external_token_emphasis] = true,
    [ts_external_token_strong] = true,
    [ts_external_token_interpreted_text] = true,
    [ts_external_token_literal] = true,
    [ts_external_token_substitution_reference] = true,
    [ts_external_token__inline_target] = true,
    [ts_external_token_footnote_reference] = true,
    [ts_external_token_reference] = true,
    [ts_external_token_standalone_hyperlink] = true,
  },
  [5] = {
    [ts_external_token__newline] = true,
    [ts_external_token__underline] = true,
    [ts_external_token__text] = true,
    [ts_external_token_emphasis] = true,
    [ts_external_token_strong] = true,
    [ts_external_token_interpreted_text] = true,
    [ts_external_token_literal] = true,
    [ts_external_token_substitution_reference] = true,
    [ts_external_token__inline_target] = true,
    [ts_external_token_footnote_reference] = true,
    [ts_external_token_reference] = true,
    [ts_external_token_standalone_hyperlink] = true,
  },
  [6] = {
    [ts_external_token__newline] = true,
    [ts_external_token__explicit_markup_start] = true,
  },
  [7] = {
    [ts_external_token__newline] = true,
    [ts_external_token__blankline] = true,
  },
  [8] = {
    [ts_external_token__newline] = true,
  },
  [9] = {
    [ts_external_token__newline] = true,
    [ts_external_token__numeric_bullet] = true,
  },
  [10] = {
    [ts_external_token__newline] = true,
    [ts_external_token__char_bullet] = true,
  },
  [11] = {
    [ts_external_token__newline] = true,
    [ts_external_token_field_name] = true,
  },
  [12] = {
    [ts_external_token__newline] = true,
    [ts_external_token__underline] = true,
  },
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_] = ACTIONS(1),
    [anon_sym_TAB] = ACTIONS(1),
    [anon_sym_2] = ACTIONS(1),
    [anon_sym_3] = ACTIONS(1),
    [aux_sym_option_list_item_token1] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [aux_sym__single_line_block_token1] = ACTIONS(1),
    [aux_sym_footnote_token1] = ACTIONS(1),
    [aux_sym_citation_token1] = ACTIONS(1),
    [aux_sym_target_token1] = ACTIONS(1),
    [anon_sym___] = ACTIONS(1),
    [aux_sym_directive_token1] = ACTIONS(1),
    [aux_sym_substitution_definition_token1] = ACTIONS(1),
    [aux_sym__embed_directive_token1] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [sym__newline] = ACTIONS(3),
    [sym__blankline] = ACTIONS(1),
    [sym__overline] = ACTIONS(1),
    [sym__underline] = ACTIONS(1),
    [sym__char_bullet] = ACTIONS(1),
    [sym__numeric_bullet] = ACTIONS(1),
    [sym_field_name] = ACTIONS(1),
    [sym__text] = ACTIONS(1),
    [sym_emphasis] = ACTIONS(1),
    [sym_strong] = ACTIONS(1),
    [sym_interpreted_text] = ACTIONS(1),
    [sym_literal] = ACTIONS(1),
    [sym_substitution_reference] = ACTIONS(1),
    [sym__inline_target] = ACTIONS(1),
    [sym_footnote_reference] = ACTIONS(1),
    [sym_reference] = ACTIONS(1),
    [sym_standalone_hyperlink] = ACTIONS(1),
    [sym__explicit_markup_start] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(102),
    [sym_section] = STATE(3),
    [sym__body_elements] = STATE(3),
    [sym_paragraph] = STATE(101),
    [sym__list] = STATE(101),
    [sym_bullet_list] = STATE(101),
    [sym__bullet_list_item] = STATE(100),
    [sym_enumerated_list] = STATE(101),
    [sym__numeric_list_item] = STATE(99),
    [sym_field_list] = STATE(101),
    [sym_field] = STATE(98),
    [sym_option_list] = STATE(101),
    [sym_option_list_item] = STATE(97),
    [sym__explicit_markup_block] = STATE(101),
    [sym__markup_block] = STATE(96),
    [sym_footnote] = STATE(96),
    [sym_citation] = STATE(96),
    [sym_target] = STATE(96),
    [sym__anonymous_target] = STATE(96),
    [sym_directive] = STATE(96),
    [sym_substitution_definition] = STATE(96),
    [sym_comment] = STATE(96),
    [aux_sym__line] = STATE(17),
    [sym__inline_markup] = STATE(52),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_paragraph_repeat1] = STATE(19),
    [aux_sym_bullet_list_repeat1] = STATE(72),
    [aux_sym_enumerated_list_repeat1] = STATE(74),
    [aux_sym_field_list_repeat1] = STATE(75),
    [aux_sym_option_list_repeat1] = STATE(76),
    [aux_sym__explicit_markup_block_repeat1] = STATE(56),
    [ts_builtin_sym_end] = ACTIONS(5),
    [aux_sym_option_list_item_token1] = ACTIONS(7),
    [anon_sym___] = ACTIONS(9),
    [aux_sym__line_token1] = ACTIONS(11),
    [sym__newline] = ACTIONS(3),
    [sym__blankline] = ACTIONS(13),
    [sym__overline] = ACTIONS(15),
    [sym__char_bullet] = ACTIONS(17),
    [sym__numeric_bullet] = ACTIONS(19),
    [sym_field_name] = ACTIONS(21),
    [sym__text] = ACTIONS(23),
    [sym_emphasis] = ACTIONS(23),
    [sym_strong] = ACTIONS(23),
    [sym_interpreted_text] = ACTIONS(23),
    [sym_literal] = ACTIONS(23),
    [sym_substitution_reference] = ACTIONS(23),
    [sym__inline_target] = ACTIONS(23),
    [sym_footnote_reference] = ACTIONS(23),
    [sym_reference] = ACTIONS(23),
    [sym_standalone_hyperlink] = ACTIONS(23),
    [sym__explicit_markup_start] = ACTIONS(25),
  },
  [2] = {
    [sym_section] = STATE(2),
    [sym__body_elements] = STATE(2),
    [sym_paragraph] = STATE(101),
    [sym__list] = STATE(101),
    [sym_bullet_list] = STATE(101),
    [sym__bullet_list_item] = STATE(100),
    [sym_enumerated_list] = STATE(101),
    [sym__numeric_list_item] = STATE(99),
    [sym_field_list] = STATE(101),
    [sym_field] = STATE(98),
    [sym_option_list] = STATE(101),
    [sym_option_list_item] = STATE(97),
    [sym__explicit_markup_block] = STATE(101),
    [sym__markup_block] = STATE(96),
    [sym_footnote] = STATE(96),
    [sym_citation] = STATE(96),
    [sym_target] = STATE(96),
    [sym__anonymous_target] = STATE(96),
    [sym_directive] = STATE(96),
    [sym_substitution_definition] = STATE(96),
    [sym_comment] = STATE(96),
    [aux_sym__line] = STATE(17),
    [sym__inline_markup] = STATE(52),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_paragraph_repeat1] = STATE(19),
    [aux_sym_bullet_list_repeat1] = STATE(72),
    [aux_sym_enumerated_list_repeat1] = STATE(74),
    [aux_sym_field_list_repeat1] = STATE(75),
    [aux_sym_option_list_repeat1] = STATE(76),
    [aux_sym__explicit_markup_block_repeat1] = STATE(56),
    [ts_builtin_sym_end] = ACTIONS(27),
    [aux_sym_option_list_item_token1] = ACTIONS(29),
    [anon_sym___] = ACTIONS(32),
    [aux_sym__line_token1] = ACTIONS(35),
    [sym__newline] = ACTIONS(3),
    [sym__blankline] = ACTIONS(38),
    [sym__overline] = ACTIONS(41),
    [sym__char_bullet] = ACTIONS(44),
    [sym__numeric_bullet] = ACTIONS(47),
    [sym_field_name] = ACTIONS(50),
    [sym__text] = ACTIONS(53),
    [sym_emphasis] = ACTIONS(53),
    [sym_strong] = ACTIONS(53),
    [sym_interpreted_text] = ACTIONS(53),
    [sym_literal] = ACTIONS(53),
    [sym_substitution_reference] = ACTIONS(53),
    [sym__inline_target] = ACTIONS(53),
    [sym_footnote_reference] = ACTIONS(53),
    [sym_reference] = ACTIONS(53),
    [sym_standalone_hyperlink] = ACTIONS(53),
    [sym__explicit_markup_start] = ACTIONS(56),
  },
  [3] = {
    [sym_section] = STATE(2),
    [sym__body_elements] = STATE(2),
    [sym_paragraph] = STATE(101),
    [sym__list] = STATE(101),
    [sym_bullet_list] = STATE(101),
    [sym__bullet_list_item] = STATE(100),
    [sym_enumerated_list] = STATE(101),
    [sym__numeric_list_item] = STATE(99),
    [sym_field_list] = STATE(101),
    [sym_field] = STATE(98),
    [sym_option_list] = STATE(101),
    [sym_option_list_item] = STATE(97),
    [sym__explicit_markup_block] = STATE(101),
    [sym__markup_block] = STATE(96),
    [sym_footnote] = STATE(96),
    [sym_citation] = STATE(96),
    [sym_target] = STATE(96),
    [sym__anonymous_target] = STATE(96),
    [sym_directive] = STATE(96),
    [sym_substitution_definition] = STATE(96),
    [sym_comment] = STATE(96),
    [aux_sym__line] = STATE(17),
    [sym__inline_markup] = STATE(52),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_paragraph_repeat1] = STATE(19),
    [aux_sym_bullet_list_repeat1] = STATE(72),
    [aux_sym_enumerated_list_repeat1] = STATE(74),
    [aux_sym_field_list_repeat1] = STATE(75),
    [aux_sym_option_list_repeat1] = STATE(76),
    [aux_sym__explicit_markup_block_repeat1] = STATE(56),
    [ts_builtin_sym_end] = ACTIONS(59),
    [aux_sym_option_list_item_token1] = ACTIONS(7),
    [anon_sym___] = ACTIONS(9),
    [aux_sym__line_token1] = ACTIONS(11),
    [sym__newline] = ACTIONS(3),
    [sym__blankline] = ACTIONS(61),
    [sym__overline] = ACTIONS(15),
    [sym__char_bullet] = ACTIONS(17),
    [sym__numeric_bullet] = ACTIONS(19),
    [sym_field_name] = ACTIONS(21),
    [sym__text] = ACTIONS(23),
    [sym_emphasis] = ACTIONS(23),
    [sym_strong] = ACTIONS(23),
    [sym_interpreted_text] = ACTIONS(23),
    [sym_literal] = ACTIONS(23),
    [sym_substitution_reference] = ACTIONS(23),
    [sym__inline_target] = ACTIONS(23),
    [sym_footnote_reference] = ACTIONS(23),
    [sym_reference] = ACTIONS(23),
    [sym_standalone_hyperlink] = ACTIONS(23),
    [sym__explicit_markup_start] = ACTIONS(25),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(65), 1,
      aux_sym__line_token1,
    ACTIONS(63), 19,
      sym__blankline,
      sym__overline,
      sym__char_bullet,
      sym__numeric_bullet,
      sym_field_name,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      sym__explicit_markup_start,
      ts_builtin_sym_end,
      aux_sym_option_list_item_token1,
      anon_sym___,
  [28] = 3,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(69), 1,
      aux_sym__line_token1,
    ACTIONS(67), 19,
      sym__blankline,
      sym__overline,
      sym__char_bullet,
      sym__numeric_bullet,
      sym_field_name,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      sym__explicit_markup_start,
      ts_builtin_sym_end,
      aux_sym_option_list_item_token1,
      anon_sym___,
  [56] = 3,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(73), 1,
      aux_sym__line_token1,
    ACTIONS(71), 19,
      sym__blankline,
      sym__overline,
      sym__char_bullet,
      sym__numeric_bullet,
      sym_field_name,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      sym__explicit_markup_start,
      ts_builtin_sym_end,
      aux_sym_option_list_item_token1,
      anon_sym___,
  [84] = 4,
    STATE(10), 1,
      aux_sym__line,
    STATE(52), 1,
      sym__inline_markup,
    ACTIONS(75), 2,
      sym__newline,
      sym__blankline,
    ACTIONS(23), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [108] = 5,
    ACTIONS(3), 1,
      sym__newline,
    STATE(8), 1,
      aux_sym_paragraph_repeat1,
    STATE(41), 1,
      aux_sym__line,
    STATE(54), 1,
      sym__inline_markup,
    ACTIONS(77), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [134] = 5,
    ACTIONS(80), 1,
      sym__newline,
    ACTIONS(82), 1,
      sym__blankline,
    STATE(10), 1,
      aux_sym__line,
    STATE(52), 1,
      sym__inline_markup,
    ACTIONS(23), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [160] = 4,
    STATE(10), 1,
      aux_sym__line,
    STATE(52), 1,
      sym__inline_markup,
    ACTIONS(87), 2,
      sym__newline,
      sym__blankline,
    ACTIONS(84), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [184] = 4,
    STATE(10), 1,
      aux_sym__line,
    STATE(52), 1,
      sym__inline_markup,
    ACTIONS(89), 2,
      sym__newline,
      sym__blankline,
    ACTIONS(23), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [208] = 4,
    STATE(10), 1,
      aux_sym__line,
    STATE(52), 1,
      sym__inline_markup,
    ACTIONS(91), 2,
      sym__newline,
      sym__blankline,
    ACTIONS(23), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [232] = 4,
    STATE(10), 1,
      aux_sym__line,
    STATE(52), 1,
      sym__inline_markup,
    ACTIONS(93), 2,
      sym__newline,
      sym__blankline,
    ACTIONS(23), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [256] = 4,
    STATE(10), 1,
      aux_sym__line,
    STATE(52), 1,
      sym__inline_markup,
    ACTIONS(95), 2,
      sym__newline,
      sym__blankline,
    ACTIONS(23), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [280] = 4,
    STATE(10), 1,
      aux_sym__line,
    STATE(52), 1,
      sym__inline_markup,
    ACTIONS(97), 2,
      sym__newline,
      sym__blankline,
    ACTIONS(23), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [304] = 4,
    STATE(10), 1,
      aux_sym__line,
    STATE(52), 1,
      sym__inline_markup,
    ACTIONS(99), 2,
      sym__newline,
      sym__blankline,
    ACTIONS(23), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [328] = 5,
    ACTIONS(101), 1,
      sym__newline,
    ACTIONS(103), 1,
      sym__blankline,
    STATE(10), 1,
      aux_sym__line,
    STATE(52), 1,
      sym__inline_markup,
    ACTIONS(23), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [354] = 4,
    STATE(10), 1,
      aux_sym__line,
    STATE(52), 1,
      sym__inline_markup,
    ACTIONS(105), 2,
      sym__newline,
      sym__blankline,
    ACTIONS(23), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [378] = 5,
    ACTIONS(3), 1,
      sym__newline,
    STATE(8), 1,
      aux_sym_paragraph_repeat1,
    STATE(9), 1,
      aux_sym__line,
    STATE(52), 1,
      sym__inline_markup,
    ACTIONS(23), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [404] = 4,
    STATE(10), 1,
      aux_sym__line,
    STATE(52), 1,
      sym__inline_markup,
    ACTIONS(107), 2,
      sym__newline,
      sym__blankline,
    ACTIONS(23), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [428] = 4,
    ACTIONS(89), 1,
      sym__newline,
    STATE(39), 1,
      aux_sym__line,
    STATE(54), 1,
      sym__inline_markup,
    ACTIONS(109), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [451] = 4,
    ACTIONS(3), 1,
      sym__newline,
    STATE(16), 1,
      aux_sym__line,
    STATE(52), 1,
      sym__inline_markup,
    ACTIONS(23), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [474] = 4,
    ACTIONS(3), 1,
      sym__newline,
    STATE(42), 1,
      aux_sym__line,
    STATE(54), 1,
      sym__inline_markup,
    ACTIONS(109), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [497] = 4,
    ACTIONS(3), 1,
      sym__newline,
    STATE(21), 1,
      aux_sym__line,
    STATE(54), 1,
      sym__inline_markup,
    ACTIONS(109), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [520] = 4,
    ACTIONS(111), 1,
      sym__newline,
    STATE(39), 1,
      aux_sym__line,
    STATE(54), 1,
      sym__inline_markup,
    ACTIONS(109), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [543] = 4,
    ACTIONS(3), 1,
      sym__newline,
    STATE(13), 1,
      aux_sym__line,
    STATE(52), 1,
      sym__inline_markup,
    ACTIONS(23), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [566] = 4,
    ACTIONS(3), 1,
      sym__newline,
    STATE(11), 1,
      aux_sym__line,
    STATE(52), 1,
      sym__inline_markup,
    ACTIONS(23), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [589] = 4,
    ACTIONS(3), 1,
      sym__newline,
    STATE(18), 1,
      aux_sym__line,
    STATE(52), 1,
      sym__inline_markup,
    ACTIONS(23), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [612] = 4,
    ACTIONS(3), 1,
      sym__newline,
    STATE(15), 1,
      aux_sym__line,
    STATE(52), 1,
      sym__inline_markup,
    ACTIONS(23), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [635] = 4,
    ACTIONS(3), 1,
      sym__newline,
    STATE(7), 1,
      aux_sym__line,
    STATE(52), 1,
      sym__inline_markup,
    ACTIONS(23), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [658] = 4,
    ACTIONS(3), 1,
      sym__newline,
    STATE(12), 1,
      aux_sym__line,
    STATE(52), 1,
      sym__inline_markup,
    ACTIONS(23), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [681] = 4,
    ACTIONS(3), 1,
      sym__newline,
    STATE(40), 1,
      aux_sym__line,
    STATE(54), 1,
      sym__inline_markup,
    ACTIONS(109), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [704] = 4,
    ACTIONS(3), 1,
      sym__newline,
    STATE(25), 1,
      aux_sym__line,
    STATE(54), 1,
      sym__inline_markup,
    ACTIONS(109), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [727] = 4,
    ACTIONS(3), 1,
      sym__newline,
    STATE(37), 1,
      aux_sym__line,
    STATE(54), 1,
      sym__inline_markup,
    ACTIONS(109), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [750] = 4,
    ACTIONS(3), 1,
      sym__newline,
    STATE(45), 1,
      aux_sym__line,
    STATE(54), 1,
      sym__inline_markup,
    ACTIONS(109), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [773] = 4,
    ACTIONS(3), 1,
      sym__newline,
    STATE(47), 1,
      aux_sym__line,
    STATE(54), 1,
      sym__inline_markup,
    ACTIONS(109), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [796] = 4,
    ACTIONS(107), 1,
      sym__newline,
    STATE(39), 1,
      aux_sym__line,
    STATE(54), 1,
      sym__inline_markup,
    ACTIONS(109), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [819] = 4,
    ACTIONS(3), 1,
      sym__newline,
    STATE(44), 1,
      aux_sym__line,
    STATE(54), 1,
      sym__inline_markup,
    ACTIONS(109), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [842] = 4,
    ACTIONS(87), 1,
      sym__newline,
    STATE(39), 1,
      aux_sym__line,
    STATE(54), 1,
      sym__inline_markup,
    ACTIONS(113), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [865] = 4,
    ACTIONS(93), 1,
      sym__newline,
    STATE(39), 1,
      aux_sym__line,
    STATE(54), 1,
      sym__inline_markup,
    ACTIONS(109), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [888] = 4,
    ACTIONS(80), 1,
      sym__newline,
    STATE(39), 1,
      aux_sym__line,
    STATE(54), 1,
      sym__inline_markup,
    ACTIONS(109), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [911] = 4,
    ACTIONS(105), 1,
      sym__newline,
    STATE(39), 1,
      aux_sym__line,
    STATE(54), 1,
      sym__inline_markup,
    ACTIONS(109), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [934] = 4,
    ACTIONS(99), 1,
      sym__newline,
    STATE(39), 1,
      aux_sym__line,
    STATE(54), 1,
      sym__inline_markup,
    ACTIONS(109), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [957] = 4,
    ACTIONS(97), 1,
      sym__newline,
    STATE(39), 1,
      aux_sym__line,
    STATE(54), 1,
      sym__inline_markup,
    ACTIONS(109), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [980] = 4,
    ACTIONS(75), 1,
      sym__newline,
    STATE(39), 1,
      aux_sym__line,
    STATE(54), 1,
      sym__inline_markup,
    ACTIONS(109), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [1003] = 4,
    ACTIONS(3), 1,
      sym__newline,
    STATE(43), 1,
      aux_sym__line,
    STATE(54), 1,
      sym__inline_markup,
    ACTIONS(109), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [1026] = 4,
    ACTIONS(91), 1,
      sym__newline,
    STATE(39), 1,
      aux_sym__line,
    STATE(54), 1,
      sym__inline_markup,
    ACTIONS(109), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [1049] = 4,
    ACTIONS(3), 1,
      sym__newline,
    STATE(14), 1,
      aux_sym__line,
    STATE(52), 1,
      sym__inline_markup,
    ACTIONS(23), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [1072] = 4,
    ACTIONS(3), 1,
      sym__newline,
    STATE(20), 1,
      aux_sym__line,
    STATE(52), 1,
      sym__inline_markup,
    ACTIONS(23), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [1095] = 4,
    ACTIONS(3), 1,
      sym__newline,
    STATE(51), 1,
      aux_sym__line,
    STATE(54), 1,
      sym__inline_markup,
    ACTIONS(109), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [1118] = 4,
    ACTIONS(95), 1,
      sym__newline,
    STATE(39), 1,
      aux_sym__line,
    STATE(54), 1,
      sym__inline_markup,
    ACTIONS(109), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [1141] = 1,
    ACTIONS(116), 13,
      sym__newline,
      sym__blankline,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [1157] = 3,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(120), 1,
      sym__underline,
    ACTIONS(118), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [1177] = 1,
    ACTIONS(116), 12,
      sym__newline,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [1192] = 5,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(122), 1,
      anon_sym___,
    ACTIONS(125), 1,
      sym__explicit_markup_start,
    STATE(55), 1,
      aux_sym__explicit_markup_block_repeat1,
    STATE(110), 8,
      sym__markup_block,
      sym_footnote,
      sym_citation,
      sym_target,
      sym__anonymous_target,
      sym_directive,
      sym_substitution_definition,
      sym_comment,
  [1215] = 5,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(9), 1,
      anon_sym___,
    ACTIONS(25), 1,
      sym__explicit_markup_start,
    STATE(55), 1,
      aux_sym__explicit_markup_block_repeat1,
    STATE(87), 8,
      sym__markup_block,
      sym_footnote,
      sym_citation,
      sym_target,
      sym__anonymous_target,
      sym_directive,
      sym_substitution_definition,
      sym_comment,
  [1238] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(118), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [1255] = 7,
    ACTIONS(130), 1,
      aux_sym_footnote_token1,
    ACTIONS(132), 1,
      aux_sym_citation_token1,
    ACTIONS(134), 1,
      aux_sym_target_token1,
    ACTIONS(136), 1,
      aux_sym_directive_token1,
    ACTIONS(138), 1,
      aux_sym_substitution_definition_token1,
    ACTIONS(140), 2,
      sym__newline,
      sym__blankline,
    ACTIONS(128), 4,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_2,
      anon_sym_3,
  [1281] = 7,
    ACTIONS(140), 1,
      sym__newline,
    ACTIONS(144), 1,
      aux_sym_footnote_token1,
    ACTIONS(146), 1,
      aux_sym_citation_token1,
    ACTIONS(148), 1,
      aux_sym_target_token1,
    ACTIONS(150), 1,
      aux_sym_directive_token1,
    ACTIONS(152), 1,
      aux_sym_substitution_definition_token1,
    ACTIONS(142), 4,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_2,
      anon_sym_3,
  [1306] = 2,
    ACTIONS(156), 2,
      sym__newline,
      sym__blankline,
    ACTIONS(154), 4,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_2,
      anon_sym_3,
  [1317] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(158), 4,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_2,
      anon_sym_3,
  [1327] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(160), 4,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_2,
      anon_sym_3,
  [1337] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(162), 4,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_2,
      anon_sym_3,
  [1347] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(164), 4,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_2,
      anon_sym_3,
  [1357] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(166), 4,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_2,
      anon_sym_3,
  [1367] = 2,
    ACTIONS(156), 1,
      sym__newline,
    ACTIONS(168), 4,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_2,
      anon_sym_3,
  [1377] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(170), 4,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_2,
      anon_sym_3,
  [1387] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(172), 4,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_2,
      anon_sym_3,
  [1397] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(174), 4,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_2,
      anon_sym_3,
  [1407] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(176), 1,
      sym__numeric_bullet,
    STATE(70), 1,
      aux_sym_enumerated_list_repeat1,
    STATE(107), 1,
      sym__numeric_list_item,
  [1420] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(179), 1,
      sym__char_bullet,
    STATE(71), 1,
      aux_sym_bullet_list_repeat1,
    STATE(112), 1,
      sym__bullet_list_item,
  [1433] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(17), 1,
      sym__char_bullet,
    STATE(71), 1,
      aux_sym_bullet_list_repeat1,
    STATE(84), 1,
      sym__bullet_list_item,
  [1446] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(182), 1,
      sym_field_name,
    STATE(73), 1,
      aux_sym_field_list_repeat1,
    STATE(113), 1,
      sym_field,
  [1459] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(19), 1,
      sym__numeric_bullet,
    STATE(70), 1,
      aux_sym_enumerated_list_repeat1,
    STATE(94), 1,
      sym__numeric_list_item,
  [1472] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(21), 1,
      sym_field_name,
    STATE(73), 1,
      aux_sym_field_list_repeat1,
    STATE(95), 1,
      sym_field,
  [1485] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(7), 1,
      aux_sym_option_list_item_token1,
    STATE(77), 1,
      aux_sym_option_list_repeat1,
    STATE(92), 1,
      sym_option_list_item,
  [1498] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(185), 1,
      aux_sym_option_list_item_token1,
    STATE(77), 1,
      aux_sym_option_list_repeat1,
    STATE(114), 1,
      sym_option_list_item,
  [1511] = 3,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(188), 1,
      aux_sym__embed_directive_token1,
    STATE(83), 1,
      sym__embed_directive,
  [1521] = 2,
    ACTIONS(190), 1,
      aux_sym_target_token2,
    ACTIONS(192), 2,
      sym__newline,
      sym__blankline,
  [1529] = 3,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(194), 1,
      aux_sym__embed_directive_token1,
    STATE(109), 1,
      sym__embed_directive,
  [1539] = 2,
    ACTIONS(196), 1,
      aux_sym_target_token2,
    ACTIONS(198), 2,
      sym__newline,
      sym__blankline,
  [1547] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(200), 2,
      sym__explicit_markup_start,
      anon_sym___,
  [1555] = 1,
    ACTIONS(202), 2,
      sym__newline,
      sym__blankline,
  [1560] = 2,
    ACTIONS(204), 1,
      sym__newline,
    ACTIONS(206), 1,
      sym__blankline,
  [1567] = 1,
    ACTIONS(208), 2,
      sym__newline,
      sym__blankline,
  [1572] = 2,
    ACTIONS(198), 1,
      sym__newline,
    ACTIONS(210), 1,
      aux_sym_target_token2,
  [1579] = 2,
    ACTIONS(212), 1,
      sym__newline,
    ACTIONS(214), 1,
      sym__blankline,
  [1586] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(216), 1,
      anon_sym_COLON_COLON,
  [1593] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(218), 1,
      sym__underline,
  [1600] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(220), 1,
      sym__numeric_bullet,
  [1607] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(222), 1,
      sym__char_bullet,
  [1614] = 2,
    ACTIONS(224), 1,
      sym__newline,
    ACTIONS(226), 1,
      sym__blankline,
  [1621] = 2,
    ACTIONS(192), 1,
      sym__newline,
    ACTIONS(228), 1,
      aux_sym_target_token2,
  [1628] = 2,
    ACTIONS(230), 1,
      sym__newline,
    ACTIONS(232), 1,
      sym__blankline,
  [1635] = 2,
    ACTIONS(234), 1,
      sym__newline,
    ACTIONS(236), 1,
      sym__blankline,
  [1642] = 2,
    ACTIONS(212), 1,
      sym__newline,
    ACTIONS(238), 1,
      sym__blankline,
  [1649] = 2,
    ACTIONS(224), 1,
      sym__newline,
    ACTIONS(240), 1,
      sym__blankline,
  [1656] = 2,
    ACTIONS(234), 1,
      sym__newline,
    ACTIONS(242), 1,
      sym__blankline,
  [1663] = 2,
    ACTIONS(230), 1,
      sym__newline,
    ACTIONS(244), 1,
      sym__blankline,
  [1670] = 2,
    ACTIONS(204), 1,
      sym__newline,
    ACTIONS(246), 1,
      sym__blankline,
  [1677] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(248), 1,
      sym__blankline,
  [1684] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(250), 1,
      ts_builtin_sym_end,
  [1691] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(252), 1,
      sym_field_name,
  [1698] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(254), 1,
      aux_sym_option_list_item_token1,
  [1705] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(256), 1,
      anon_sym_COLON_COLON,
  [1712] = 1,
    ACTIONS(258), 2,
      sym__newline,
      sym__blankline,
  [1717] = 1,
    ACTIONS(230), 1,
      sym__newline,
  [1721] = 1,
    ACTIONS(258), 1,
      sym__newline,
  [1725] = 1,
    ACTIONS(202), 1,
      sym__newline,
  [1729] = 1,
    ACTIONS(212), 1,
      sym__newline,
  [1733] = 1,
    ACTIONS(208), 1,
      sym__newline,
  [1737] = 1,
    ACTIONS(204), 1,
      sym__newline,
  [1741] = 1,
    ACTIONS(234), 1,
      sym__newline,
  [1745] = 1,
    ACTIONS(224), 1,
      sym__newline,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 28,
  [SMALL_STATE(6)] = 56,
  [SMALL_STATE(7)] = 84,
  [SMALL_STATE(8)] = 108,
  [SMALL_STATE(9)] = 134,
  [SMALL_STATE(10)] = 160,
  [SMALL_STATE(11)] = 184,
  [SMALL_STATE(12)] = 208,
  [SMALL_STATE(13)] = 232,
  [SMALL_STATE(14)] = 256,
  [SMALL_STATE(15)] = 280,
  [SMALL_STATE(16)] = 304,
  [SMALL_STATE(17)] = 328,
  [SMALL_STATE(18)] = 354,
  [SMALL_STATE(19)] = 378,
  [SMALL_STATE(20)] = 404,
  [SMALL_STATE(21)] = 428,
  [SMALL_STATE(22)] = 451,
  [SMALL_STATE(23)] = 474,
  [SMALL_STATE(24)] = 497,
  [SMALL_STATE(25)] = 520,
  [SMALL_STATE(26)] = 543,
  [SMALL_STATE(27)] = 566,
  [SMALL_STATE(28)] = 589,
  [SMALL_STATE(29)] = 612,
  [SMALL_STATE(30)] = 635,
  [SMALL_STATE(31)] = 658,
  [SMALL_STATE(32)] = 681,
  [SMALL_STATE(33)] = 704,
  [SMALL_STATE(34)] = 727,
  [SMALL_STATE(35)] = 750,
  [SMALL_STATE(36)] = 773,
  [SMALL_STATE(37)] = 796,
  [SMALL_STATE(38)] = 819,
  [SMALL_STATE(39)] = 842,
  [SMALL_STATE(40)] = 865,
  [SMALL_STATE(41)] = 888,
  [SMALL_STATE(42)] = 911,
  [SMALL_STATE(43)] = 934,
  [SMALL_STATE(44)] = 957,
  [SMALL_STATE(45)] = 980,
  [SMALL_STATE(46)] = 1003,
  [SMALL_STATE(47)] = 1026,
  [SMALL_STATE(48)] = 1049,
  [SMALL_STATE(49)] = 1072,
  [SMALL_STATE(50)] = 1095,
  [SMALL_STATE(51)] = 1118,
  [SMALL_STATE(52)] = 1141,
  [SMALL_STATE(53)] = 1157,
  [SMALL_STATE(54)] = 1177,
  [SMALL_STATE(55)] = 1192,
  [SMALL_STATE(56)] = 1215,
  [SMALL_STATE(57)] = 1238,
  [SMALL_STATE(58)] = 1255,
  [SMALL_STATE(59)] = 1281,
  [SMALL_STATE(60)] = 1306,
  [SMALL_STATE(61)] = 1317,
  [SMALL_STATE(62)] = 1327,
  [SMALL_STATE(63)] = 1337,
  [SMALL_STATE(64)] = 1347,
  [SMALL_STATE(65)] = 1357,
  [SMALL_STATE(66)] = 1367,
  [SMALL_STATE(67)] = 1377,
  [SMALL_STATE(68)] = 1387,
  [SMALL_STATE(69)] = 1397,
  [SMALL_STATE(70)] = 1407,
  [SMALL_STATE(71)] = 1420,
  [SMALL_STATE(72)] = 1433,
  [SMALL_STATE(73)] = 1446,
  [SMALL_STATE(74)] = 1459,
  [SMALL_STATE(75)] = 1472,
  [SMALL_STATE(76)] = 1485,
  [SMALL_STATE(77)] = 1498,
  [SMALL_STATE(78)] = 1511,
  [SMALL_STATE(79)] = 1521,
  [SMALL_STATE(80)] = 1529,
  [SMALL_STATE(81)] = 1539,
  [SMALL_STATE(82)] = 1547,
  [SMALL_STATE(83)] = 1555,
  [SMALL_STATE(84)] = 1560,
  [SMALL_STATE(85)] = 1567,
  [SMALL_STATE(86)] = 1572,
  [SMALL_STATE(87)] = 1579,
  [SMALL_STATE(88)] = 1586,
  [SMALL_STATE(89)] = 1593,
  [SMALL_STATE(90)] = 1600,
  [SMALL_STATE(91)] = 1607,
  [SMALL_STATE(92)] = 1614,
  [SMALL_STATE(93)] = 1621,
  [SMALL_STATE(94)] = 1628,
  [SMALL_STATE(95)] = 1635,
  [SMALL_STATE(96)] = 1642,
  [SMALL_STATE(97)] = 1649,
  [SMALL_STATE(98)] = 1656,
  [SMALL_STATE(99)] = 1663,
  [SMALL_STATE(100)] = 1670,
  [SMALL_STATE(101)] = 1677,
  [SMALL_STATE(102)] = 1684,
  [SMALL_STATE(103)] = 1691,
  [SMALL_STATE(104)] = 1698,
  [SMALL_STATE(105)] = 1705,
  [SMALL_STATE(106)] = 1712,
  [SMALL_STATE(107)] = 1717,
  [SMALL_STATE(108)] = 1721,
  [SMALL_STATE(109)] = 1725,
  [SMALL_STATE(110)] = 1729,
  [SMALL_STATE(111)] = 1733,
  [SMALL_STATE(112)] = 1737,
  [SMALL_STATE(113)] = 1741,
  [SMALL_STATE(114)] = 1745,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(49),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(81),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(52),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(2),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(33),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(67),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(63),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(64),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(52),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(58),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__body_elements, 2),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__body_elements, 2),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 4, .production_id = 3),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section, 4, .production_id = 3),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 3, .production_id = 2),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section, 3, .production_id = 2),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_footnote, 3),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(54),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 2),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__line, 2), SHIFT_REPEAT(52),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__line, 2),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__numeric_list_item, 3),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_citation, 3),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__bullet_list_item, 3),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 4),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__embed_directive, 4),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 1),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 3, .production_id = 1),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_option_list_item, 2),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [113] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__line, 2), SHIFT_REPEAT(54),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__line, 1),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [122] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__explicit_markup_block_repeat1, 2), SHIFT_REPEAT(86),
  [125] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__explicit_markup_block_repeat1, 2), SHIFT_REPEAT(59),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [132] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1),
  [142] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [146] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 2),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [176] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enumerated_list_repeat1, 2), SHIFT_REPEAT(61),
  [179] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bullet_list_repeat1, 2), SHIFT_REPEAT(62),
  [182] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_field_list_repeat1, 2), SHIFT_REPEAT(68),
  [185] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_option_list_repeat1, 2), SHIFT_REPEAT(34),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target, 2),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__anonymous_target, 1),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__explicit_markup_block_repeat1, 2),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_substitution_definition, 3),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bullet_list, 2),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__anonymous_target, 2),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__explicit_markup_block, 2),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enumerated_list_repeat1, 2),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_bullet_list_repeat1, 2),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_option_list, 2),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enumerated_list, 2),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_list, 2),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__explicit_markup_block, 1),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_option_list, 1),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_list, 1),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enumerated_list, 1),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bullet_list, 1),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [250] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_field_list_repeat1, 2),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_option_list_repeat1, 2),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target, 3),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_rst_external_scanner_create(void);
void tree_sitter_rst_external_scanner_destroy(void *);
bool tree_sitter_rst_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_rst_external_scanner_serialize(void *, char *);
void tree_sitter_rst_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_rst(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const unsigned short *)ts_parse_table,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .symbol_names = ts_symbol_names,
    .public_symbol_map = ts_symbol_map,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .external_scanner = {
      (const bool *)ts_external_scanner_states,
      ts_external_scanner_symbol_map,
      tree_sitter_rst_external_scanner_create,
      tree_sitter_rst_external_scanner_destroy,
      tree_sitter_rst_external_scanner_scan,
      tree_sitter_rst_external_scanner_serialize,
      tree_sitter_rst_external_scanner_deserialize,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
