#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 11
#define STATE_COUNT 142
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 73
#define ALIAS_COUNT 1
#define TOKEN_COUNT 34
#define EXTERNAL_TOKEN_COUNT 17
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4

enum {
  anon_sym_ = 1,
  anon_sym_TAB = 2,
  anon_sym_2 = 3,
  anon_sym_3 = 4,
  aux_sym_field_token2 = 5,
  anon_sym_PIPE = 6,
  aux_sym_footnote_token1 = 7,
  aux_sym_citation_token1 = 8,
  aux_sym_target_token1 = 9,
  aux_sym_target_token2 = 10,
  anon_sym___ = 11,
  aux_sym_directive_token1 = 12,
  aux_sym_substitution_definition_token1 = 13,
  aux_sym__embed_directive_token1 = 14,
  anon_sym_COLON_COLON = 15,
  aux_sym__line_token1 = 16,
  sym__newline = 17,
  sym__blankline = 18,
  sym__overline = 19,
  sym__underline = 20,
  sym__char_bullet = 21,
  sym__numeric_bullet = 22,
  sym__text = 23,
  sym_emphasis = 24,
  sym_strong = 25,
  sym_interpreted_text = 26,
  sym_literal = 27,
  sym_substitution_reference = 28,
  sym__inline_target = 29,
  sym_footnote_reference = 30,
  sym_reference = 31,
  sym_standalone_hyperlink = 32,
  sym__explicit_markup_start = 33,
  sym_document = 34,
  sym_section = 35,
  sym__body_elements = 36,
  sym_paragraph = 37,
  sym__list = 38,
  sym_bullet_list = 39,
  sym__bullet_list_item = 40,
  sym_enumerated_list = 41,
  sym__numeric_list_item = 42,
  sym__markup_block = 43,
  sym__footnote_block = 44,
  sym_footnote = 45,
  sym__citation_block = 46,
  sym_citation = 47,
  sym__hyperlink_target_block = 48,
  sym_target = 49,
  sym__anoynymous_hyperlink_target_block = 50,
  sym__anonymous_target = 51,
  sym__directive_block = 52,
  sym_directive = 53,
  sym__substitution_definition_block = 54,
  sym_substitution_definition = 55,
  sym__embed_directive = 56,
  sym__comment_block = 57,
  sym_comment = 58,
  aux_sym__line = 59,
  sym__inline_markup = 60,
  aux_sym_document_repeat1 = 61,
  aux_sym_paragraph_repeat1 = 62,
  aux_sym_bullet_list_repeat1 = 63,
  aux_sym_enumerated_list_repeat1 = 64,
  aux_sym_field_repeat1 = 65,
  aux_sym__footnote_block_repeat1 = 66,
  aux_sym__citation_block_repeat1 = 67,
  aux_sym__hyperlink_target_block_repeat1 = 68,
  aux_sym__anoynymous_hyperlink_target_block_repeat1 = 69,
  aux_sym__directive_block_repeat1 = 70,
  aux_sym__substitution_definition_block_repeat1 = 71,
  aux_sym__comment_block_repeat1 = 72,
  alias_sym_title = 73,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_] = " ",
  [anon_sym_TAB] = "\t",
  [anon_sym_2] = "",
  [anon_sym_3] = "\f",
  [aux_sym_field_token2] = "field_token2",
  [anon_sym_PIPE] = "|",
  [aux_sym_footnote_token1] = "footnote_token1",
  [aux_sym_citation_token1] = "citation_token1",
  [aux_sym_target_token1] = "target_token1",
  [aux_sym_target_token2] = "target_token2",
  [anon_sym___] = "__",
  [aux_sym_directive_token1] = "directive_token1",
  [aux_sym_substitution_definition_token1] = "substitution_definition_token1",
  [aux_sym__embed_directive_token1] = "_embed_directive_token1",
  [anon_sym_COLON_COLON] = "::",
  [aux_sym__line_token1] = "_line_token1",
  [sym__newline] = "_newline",
  [sym__blankline] = "_blankline",
  [sym__overline] = "_overline",
  [sym__underline] = "_underline",
  [sym__char_bullet] = "_char_bullet",
  [sym__numeric_bullet] = "_numeric_bullet",
  [sym__text] = "_text",
  [sym_emphasis] = "emphasis",
  [sym_strong] = "strong",
  [sym_interpreted_text] = "interpreted_text",
  [sym_literal] = "literal",
  [sym_substitution_reference] = "substitution_reference",
  [sym__inline_target] = "target",
  [sym_footnote_reference] = "footnote_reference",
  [sym_reference] = "reference",
  [sym_standalone_hyperlink] = "standalone_hyperlink",
  [sym__explicit_markup_start] = "_explicit_markup_start",
  [sym_document] = "document",
  [sym_section] = "section",
  [sym__body_elements] = "_body_elements",
  [sym_paragraph] = "paragraph",
  [sym__list] = "_list",
  [sym_bullet_list] = "bullet_list",
  [sym__bullet_list_item] = "list_item",
  [sym_enumerated_list] = "enumerated_list",
  [sym__numeric_list_item] = "list_item",
  [sym__markup_block] = "_markup_block",
  [sym__footnote_block] = "_footnote_block",
  [sym_footnote] = "footnote",
  [sym__citation_block] = "_citation_block",
  [sym_citation] = "citation",
  [sym__hyperlink_target_block] = "_hyperlink_target_block",
  [sym_target] = "target",
  [sym__anoynymous_hyperlink_target_block] = "_anoynymous_hyperlink_target_block",
  [sym__anonymous_target] = "target",
  [sym__directive_block] = "_directive_block",
  [sym_directive] = "directive",
  [sym__substitution_definition_block] = "_substitution_definition_block",
  [sym_substitution_definition] = "substitution_definition",
  [sym__embed_directive] = "_embed_directive",
  [sym__comment_block] = "_comment_block",
  [sym_comment] = "comment",
  [aux_sym__line] = "_line",
  [sym__inline_markup] = "_inline_markup",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_paragraph_repeat1] = "paragraph_repeat1",
  [aux_sym_bullet_list_repeat1] = "bullet_list_repeat1",
  [aux_sym_enumerated_list_repeat1] = "enumerated_list_repeat1",
  [aux_sym_field_repeat1] = "field_repeat1",
  [aux_sym__footnote_block_repeat1] = "_footnote_block_repeat1",
  [aux_sym__citation_block_repeat1] = "_citation_block_repeat1",
  [aux_sym__hyperlink_target_block_repeat1] = "_hyperlink_target_block_repeat1",
  [aux_sym__anoynymous_hyperlink_target_block_repeat1] = "_anoynymous_hyperlink_target_block_repeat1",
  [aux_sym__directive_block_repeat1] = "_directive_block_repeat1",
  [aux_sym__substitution_definition_block_repeat1] = "_substitution_definition_block_repeat1",
  [aux_sym__comment_block_repeat1] = "_comment_block_repeat1",
  [alias_sym_title] = "title",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_] = anon_sym_,
  [anon_sym_TAB] = anon_sym_TAB,
  [anon_sym_2] = anon_sym_2,
  [anon_sym_3] = anon_sym_3,
  [aux_sym_field_token2] = aux_sym_field_token2,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [aux_sym_footnote_token1] = aux_sym_footnote_token1,
  [aux_sym_citation_token1] = aux_sym_citation_token1,
  [aux_sym_target_token1] = aux_sym_target_token1,
  [aux_sym_target_token2] = aux_sym_target_token2,
  [anon_sym___] = anon_sym___,
  [aux_sym_directive_token1] = aux_sym_directive_token1,
  [aux_sym_substitution_definition_token1] = aux_sym_substitution_definition_token1,
  [aux_sym__embed_directive_token1] = aux_sym__embed_directive_token1,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [aux_sym__line_token1] = aux_sym__line_token1,
  [sym__newline] = sym__newline,
  [sym__blankline] = sym__blankline,
  [sym__overline] = sym__overline,
  [sym__underline] = sym__underline,
  [sym__char_bullet] = sym__char_bullet,
  [sym__numeric_bullet] = sym__numeric_bullet,
  [sym__text] = sym__text,
  [sym_emphasis] = sym_emphasis,
  [sym_strong] = sym_strong,
  [sym_interpreted_text] = sym_interpreted_text,
  [sym_literal] = sym_literal,
  [sym_substitution_reference] = sym_substitution_reference,
  [sym__inline_target] = sym_target,
  [sym_footnote_reference] = sym_footnote_reference,
  [sym_reference] = sym_reference,
  [sym_standalone_hyperlink] = sym_standalone_hyperlink,
  [sym__explicit_markup_start] = sym__explicit_markup_start,
  [sym_document] = sym_document,
  [sym_section] = sym_section,
  [sym__body_elements] = sym__body_elements,
  [sym_paragraph] = sym_paragraph,
  [sym__list] = sym__list,
  [sym_bullet_list] = sym_bullet_list,
  [sym__bullet_list_item] = sym__bullet_list_item,
  [sym_enumerated_list] = sym_enumerated_list,
  [sym__numeric_list_item] = sym__bullet_list_item,
  [sym__markup_block] = sym__markup_block,
  [sym__footnote_block] = sym__footnote_block,
  [sym_footnote] = sym_footnote,
  [sym__citation_block] = sym__citation_block,
  [sym_citation] = sym_citation,
  [sym__hyperlink_target_block] = sym__hyperlink_target_block,
  [sym_target] = sym_target,
  [sym__anoynymous_hyperlink_target_block] = sym__anoynymous_hyperlink_target_block,
  [sym__anonymous_target] = sym_target,
  [sym__directive_block] = sym__directive_block,
  [sym_directive] = sym_directive,
  [sym__substitution_definition_block] = sym__substitution_definition_block,
  [sym_substitution_definition] = sym_substitution_definition,
  [sym__embed_directive] = sym__embed_directive,
  [sym__comment_block] = sym__comment_block,
  [sym_comment] = sym_comment,
  [aux_sym__line] = aux_sym__line,
  [sym__inline_markup] = sym__inline_markup,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_paragraph_repeat1] = aux_sym_paragraph_repeat1,
  [aux_sym_bullet_list_repeat1] = aux_sym_bullet_list_repeat1,
  [aux_sym_enumerated_list_repeat1] = aux_sym_enumerated_list_repeat1,
  [aux_sym_field_repeat1] = aux_sym_field_repeat1,
  [aux_sym__footnote_block_repeat1] = aux_sym__footnote_block_repeat1,
  [aux_sym__citation_block_repeat1] = aux_sym__citation_block_repeat1,
  [aux_sym__hyperlink_target_block_repeat1] = aux_sym__hyperlink_target_block_repeat1,
  [aux_sym__anoynymous_hyperlink_target_block_repeat1] = aux_sym__anoynymous_hyperlink_target_block_repeat1,
  [aux_sym__directive_block_repeat1] = aux_sym__directive_block_repeat1,
  [aux_sym__substitution_definition_block_repeat1] = aux_sym__substitution_definition_block_repeat1,
  [aux_sym__comment_block_repeat1] = aux_sym__comment_block_repeat1,
  [alias_sym_title] = alias_sym_title,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TAB] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_3] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_field_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_footnote_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_citation_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_target_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_target_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym___] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_directive_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_substitution_definition_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__embed_directive_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__line_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym__blankline] = {
    .visible = false,
    .named = true,
  },
  [sym__overline] = {
    .visible = false,
    .named = true,
  },
  [sym__underline] = {
    .visible = false,
    .named = true,
  },
  [sym__char_bullet] = {
    .visible = false,
    .named = true,
  },
  [sym__numeric_bullet] = {
    .visible = false,
    .named = true,
  },
  [sym__text] = {
    .visible = false,
    .named = true,
  },
  [sym_emphasis] = {
    .visible = true,
    .named = true,
  },
  [sym_strong] = {
    .visible = true,
    .named = true,
  },
  [sym_interpreted_text] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_substitution_reference] = {
    .visible = true,
    .named = true,
  },
  [sym__inline_target] = {
    .visible = true,
    .named = true,
  },
  [sym_footnote_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_standalone_hyperlink] = {
    .visible = true,
    .named = true,
  },
  [sym__explicit_markup_start] = {
    .visible = false,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym__body_elements] = {
    .visible = false,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [sym__list] = {
    .visible = false,
    .named = true,
  },
  [sym_bullet_list] = {
    .visible = true,
    .named = true,
  },
  [sym__bullet_list_item] = {
    .visible = true,
    .named = true,
  },
  [sym_enumerated_list] = {
    .visible = true,
    .named = true,
  },
  [sym__numeric_list_item] = {
    .visible = true,
    .named = true,
  },
  [sym__markup_block] = {
    .visible = false,
    .named = true,
  },
  [sym__footnote_block] = {
    .visible = false,
    .named = true,
  },
  [sym_footnote] = {
    .visible = true,
    .named = true,
  },
  [sym__citation_block] = {
    .visible = false,
    .named = true,
  },
  [sym_citation] = {
    .visible = true,
    .named = true,
  },
  [sym__hyperlink_target_block] = {
    .visible = false,
    .named = true,
  },
  [sym_target] = {
    .visible = true,
    .named = true,
  },
  [sym__anoynymous_hyperlink_target_block] = {
    .visible = false,
    .named = true,
  },
  [sym__anonymous_target] = {
    .visible = true,
    .named = true,
  },
  [sym__directive_block] = {
    .visible = false,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym__substitution_definition_block] = {
    .visible = false,
    .named = true,
  },
  [sym_substitution_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__embed_directive] = {
    .visible = false,
    .named = true,
  },
  [sym__comment_block] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__line] = {
    .visible = false,
    .named = false,
  },
  [sym__inline_markup] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paragraph_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_bullet_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enumerated_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_field_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__footnote_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__citation_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__hyperlink_target_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__anoynymous_hyperlink_target_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__directive_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__substitution_definition_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__comment_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_title] = {
    .visible = true,
    .named = true,
  },
};

static TSSymbol ts_alias_sequences[3][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_title,
  },
  [2] = {
    [1] = alias_sym_title,
  },
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(39);
      if (lookahead == '\t') ADVANCE(42);
      if (lookahead == 11) ADVANCE(44);
      if (lookahead == '\f') ADVANCE(46);
      if (lookahead == ' ') ADVANCE(40);
      if (lookahead == '|') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(48);
      END_STATE();
    case 1:
      if (lookahead == '\t') ADVANCE(42);
      if (lookahead == 11) ADVANCE(44);
      if (lookahead == '\f') ADVANCE(46);
      if (lookahead == ' ') ADVANCE(40);
      END_STATE();
    case 2:
      if (lookahead == '\t') ADVANCE(43);
      if (lookahead == 11) ADVANCE(45);
      if (lookahead == '\f') ADVANCE(47);
      if (lookahead == ' ') ADVANCE(41);
      if (lookahead == ':') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == '*') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 4:
      if (lookahead == ':') ADVANCE(60);
      END_STATE();
    case 5:
      if (lookahead == ':') ADVANCE(52);
      END_STATE();
    case 6:
      if (lookahead == ':') ADVANCE(52);
      if (lookahead == '_') ADVANCE(20);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == ':') ADVANCE(52);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 8:
      if (lookahead == ':') ADVANCE(53);
      if (lookahead == '_') ADVANCE(11);
      if (lookahead == '`') ADVANCE(6);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == ':') ADVANCE(53);
      if (lookahead == '`') ADVANCE(20);
      if (lookahead != 0) ADVANCE(11);
      END_STATE();
    case 10:
      if (lookahead == ':') ADVANCE(56);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          lookahead == '_') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 11:
      if (lookahead == ':') ADVANCE(22);
      if (lookahead == '_') ADVANCE(11);
      if (lookahead == '`') ADVANCE(6);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 12:
      if (lookahead == ':') ADVANCE(10);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          lookahead == '_') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 13:
      if (lookahead == '[') ADVANCE(35);
      END_STATE();
    case 14:
      if (lookahead == ']') ADVANCE(29);
      END_STATE();
    case 15:
      if (lookahead == ']') ADVANCE(29);
      if (lookahead == '-' ||
          lookahead == '.' ||
          lookahead == '_') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 16:
      if (lookahead == ']') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 17:
      if (lookahead == ']') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 18:
      if (lookahead == ']') ADVANCE(30);
      if (lookahead == '-' ||
          lookahead == '.' ||
          lookahead == '_') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      if (lookahead == '_') ADVANCE(55);
      END_STATE();
    case 20:
      if (lookahead == '_') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(6);
      END_STATE();
    case 21:
      if (lookahead == '_') ADVANCE(5);
      if (lookahead == '`') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(7);
      END_STATE();
    case 22:
      if (lookahead == '`') ADVANCE(5);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 23:
      if (lookahead == '|') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 24:
      if (lookahead == '|') ADVANCE(25);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(24);
      END_STATE();
    case 25:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(58);
      if (lookahead == 11 ||
          lookahead == '\f') ADVANCE(57);
      if (lookahead == '\r') ADVANCE(27);
      if (lookahead == '|') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(24);
      END_STATE();
    case 26:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(58);
      if (lookahead == 11 ||
          lookahead == '\f') ADVANCE(57);
      if (lookahead == '\r') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(24);
      END_STATE();
    case 27:
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(24);
      END_STATE();
    case 28:
      if (lookahead == '-' ||
          lookahead == '.' ||
          lookahead == '_') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 29:
      if (lookahead == '\t' ||
          lookahead == 11 ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(50);
      END_STATE();
    case 30:
      if (lookahead == '\t' ||
          lookahead == 11 ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(51);
      END_STATE();
    case 31:
      if (lookahead == '\t' ||
          lookahead == 11 ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(13);
      END_STATE();
    case 32:
      if (lookahead == '\t' ||
          lookahead == 11 ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(37);
      END_STATE();
    case 33:
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          lookahead == ':' ||
          lookahead == '_') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 34:
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          lookahead == ':' ||
          lookahead == '_') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 35:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 36:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(48);
      END_STATE();
    case 37:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(54);
      END_STATE();
    case 38:
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ') ADVANCE(23);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_);
      if (lookahead == '[') ADVANCE(3);
      if (lookahead == '_') ADVANCE(21);
      if (lookahead == '|') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_TAB);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_TAB);
      if (lookahead == '[') ADVANCE(3);
      if (lookahead == '_') ADVANCE(21);
      if (lookahead == '|') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_2);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_2);
      if (lookahead == '[') ADVANCE(3);
      if (lookahead == '_') ADVANCE(21);
      if (lookahead == '|') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_3);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_3);
      if (lookahead == '[') ADVANCE(3);
      if (lookahead == '_') ADVANCE(21);
      if (lookahead == '|') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_field_token2);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_footnote_token1);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_citation_token1);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_target_token1);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_target_token1);
      if (lookahead == '`') ADVANCE(5);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_target_token2);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym___);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_directive_token1);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          lookahead == ':' ||
          lookahead == '_') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_substitution_definition_token1);
      if (lookahead == '|') ADVANCE(25);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(24);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_substitution_definition_token1);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(24);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym__embed_directive_token1);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          lookahead == ':' ||
          lookahead == '_') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym__line_token1);
      if (lookahead == '\t' ||
          lookahead == 11 ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym__line_token1);
      if (eof) ADVANCE(39);
      if (lookahead == '\t' ||
          lookahead == 11 ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(61);
      if (lookahead == '_') ADVANCE(19);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 62, .external_lex_state = 2},
  [2] = {.lex_state = 62, .external_lex_state = 2},
  [3] = {.lex_state = 62, .external_lex_state = 2},
  [4] = {.lex_state = 62, .external_lex_state = 2},
  [5] = {.lex_state = 62, .external_lex_state = 2},
  [6] = {.lex_state = 62, .external_lex_state = 2},
  [7] = {.lex_state = 62, .external_lex_state = 3},
  [8] = {.lex_state = 62, .external_lex_state = 3},
  [9] = {.lex_state = 62, .external_lex_state = 4},
  [10] = {.lex_state = 62, .external_lex_state = 4},
  [11] = {.lex_state = 62, .external_lex_state = 4},
  [12] = {.lex_state = 62, .external_lex_state = 4},
  [13] = {.lex_state = 62, .external_lex_state = 4},
  [14] = {.lex_state = 62, .external_lex_state = 4},
  [15] = {.lex_state = 62, .external_lex_state = 4},
  [16] = {.lex_state = 62, .external_lex_state = 4},
  [17] = {.lex_state = 62, .external_lex_state = 3},
  [18] = {.lex_state = 62, .external_lex_state = 3},
  [19] = {.lex_state = 62, .external_lex_state = 3},
  [20] = {.lex_state = 62, .external_lex_state = 3},
  [21] = {.lex_state = 62, .external_lex_state = 3},
  [22] = {.lex_state = 62, .external_lex_state = 3},
  [23] = {.lex_state = 62, .external_lex_state = 3},
  [24] = {.lex_state = 62, .external_lex_state = 3},
  [25] = {.lex_state = 62, .external_lex_state = 3},
  [26] = {.lex_state = 62, .external_lex_state = 3},
  [27] = {.lex_state = 62, .external_lex_state = 3},
  [28] = {.lex_state = 62, .external_lex_state = 3},
  [29] = {.lex_state = 62, .external_lex_state = 3},
  [30] = {.lex_state = 62, .external_lex_state = 3},
  [31] = {.lex_state = 62, .external_lex_state = 3},
  [32] = {.lex_state = 62, .external_lex_state = 3},
  [33] = {.lex_state = 62, .external_lex_state = 3},
  [34] = {.lex_state = 62, .external_lex_state = 3},
  [35] = {.lex_state = 62, .external_lex_state = 3},
  [36] = {.lex_state = 62, .external_lex_state = 5},
  [37] = {.lex_state = 62, .external_lex_state = 4},
  [38] = {.lex_state = 62, .external_lex_state = 3},
  [39] = {.lex_state = 62, .external_lex_state = 3},
  [40] = {.lex_state = 2, .external_lex_state = 6},
  [41] = {.lex_state = 1, .external_lex_state = 6},
  [42] = {.lex_state = 1, .external_lex_state = 6},
  [43] = {.lex_state = 1, .external_lex_state = 7},
  [44] = {.lex_state = 1, .external_lex_state = 7},
  [45] = {.lex_state = 1, .external_lex_state = 7},
  [46] = {.lex_state = 1, .external_lex_state = 7},
  [47] = {.lex_state = 1, .external_lex_state = 7},
  [48] = {.lex_state = 1, .external_lex_state = 7},
  [49] = {.lex_state = 1, .external_lex_state = 7},
  [50] = {.lex_state = 1, .external_lex_state = 7},
  [51] = {.lex_state = 36, .external_lex_state = 6},
  [52] = {.lex_state = 0, .external_lex_state = 8},
  [53] = {.lex_state = 0, .external_lex_state = 8},
  [54] = {.lex_state = 0, .external_lex_state = 8},
  [55] = {.lex_state = 36, .external_lex_state = 6},
  [56] = {.lex_state = 0, .external_lex_state = 8},
  [57] = {.lex_state = 0, .external_lex_state = 9},
  [58] = {.lex_state = 0, .external_lex_state = 8},
  [59] = {.lex_state = 0, .external_lex_state = 10},
  [60] = {.lex_state = 0, .external_lex_state = 8},
  [61] = {.lex_state = 0, .external_lex_state = 9},
  [62] = {.lex_state = 0, .external_lex_state = 8},
  [63] = {.lex_state = 0, .external_lex_state = 10},
  [64] = {.lex_state = 0, .external_lex_state = 8},
  [65] = {.lex_state = 0, .external_lex_state = 8},
  [66] = {.lex_state = 0, .external_lex_state = 8},
  [67] = {.lex_state = 0, .external_lex_state = 8},
  [68] = {.lex_state = 0, .external_lex_state = 8},
  [69] = {.lex_state = 62, .external_lex_state = 7},
  [70] = {.lex_state = 62, .external_lex_state = 7},
  [71] = {.lex_state = 36, .external_lex_state = 6},
  [72] = {.lex_state = 36, .external_lex_state = 7},
  [73] = {.lex_state = 2, .external_lex_state = 7},
  [74] = {.lex_state = 36, .external_lex_state = 7},
  [75] = {.lex_state = 36, .external_lex_state = 7},
  [76] = {.lex_state = 36, .external_lex_state = 7},
  [77] = {.lex_state = 32, .external_lex_state = 6},
  [78] = {.lex_state = 36, .external_lex_state = 7},
  [79] = {.lex_state = 2, .external_lex_state = 7},
  [80] = {.lex_state = 36, .external_lex_state = 7},
  [81] = {.lex_state = 36, .external_lex_state = 7},
  [82] = {.lex_state = 32, .external_lex_state = 6},
  [83] = {.lex_state = 2, .external_lex_state = 7},
  [84] = {.lex_state = 0, .external_lex_state = 6},
  [85] = {.lex_state = 0, .external_lex_state = 8},
  [86] = {.lex_state = 0, .external_lex_state = 8},
  [87] = {.lex_state = 0, .external_lex_state = 10},
  [88] = {.lex_state = 0, .external_lex_state = 9},
  [89] = {.lex_state = 0, .external_lex_state = 6},
  [90] = {.lex_state = 2, .external_lex_state = 7},
  [91] = {.lex_state = 0, .external_lex_state = 6},
  [92] = {.lex_state = 0, .external_lex_state = 6},
  [93] = {.lex_state = 2, .external_lex_state = 7},
  [94] = {.lex_state = 0, .external_lex_state = 7},
  [95] = {.lex_state = 0, .external_lex_state = 8},
  [96] = {.lex_state = 2, .external_lex_state = 7},
  [97] = {.lex_state = 0, .external_lex_state = 8},
  [98] = {.lex_state = 0, .external_lex_state = 6},
  [99] = {.lex_state = 0, .external_lex_state = 6},
  [100] = {.lex_state = 0, .external_lex_state = 6},
  [101] = {.lex_state = 0, .external_lex_state = 6},
  [102] = {.lex_state = 0, .external_lex_state = 8},
  [103] = {.lex_state = 0, .external_lex_state = 11},
  [104] = {.lex_state = 0, .external_lex_state = 6},
  [105] = {.lex_state = 0, .external_lex_state = 6},
  [106] = {.lex_state = 2, .external_lex_state = 7},
  [107] = {.lex_state = 0, .external_lex_state = 6},
  [108] = {.lex_state = 32, .external_lex_state = 7},
  [109] = {.lex_state = 2, .external_lex_state = 7},
  [110] = {.lex_state = 0, .external_lex_state = 6},
  [111] = {.lex_state = 0, .external_lex_state = 6},
  [112] = {.lex_state = 2, .external_lex_state = 7},
  [113] = {.lex_state = 0, .external_lex_state = 6},
  [114] = {.lex_state = 31, .external_lex_state = 7},
  [115] = {.lex_state = 32, .external_lex_state = 7},
  [116] = {.lex_state = 0, .external_lex_state = 6},
  [117] = {.lex_state = 2, .external_lex_state = 7},
  [118] = {.lex_state = 0, .external_lex_state = 6},
  [119] = {.lex_state = 62, .external_lex_state = 7},
  [120] = {.lex_state = 31, .external_lex_state = 7},
  [121] = {.lex_state = 2, .external_lex_state = 7},
  [122] = {.lex_state = 2, .external_lex_state = 7},
  [123] = {.lex_state = 0, .external_lex_state = 6},
  [124] = {.lex_state = 0, .external_lex_state = 6},
  [125] = {.lex_state = 0, .external_lex_state = 6},
  [126] = {.lex_state = 0, .external_lex_state = 8},
  [127] = {.lex_state = 0, .external_lex_state = 6},
  [128] = {.lex_state = 0, .external_lex_state = 6},
  [129] = {.lex_state = 0, .external_lex_state = 6},
  [130] = {.lex_state = 0, .external_lex_state = 7},
  [131] = {.lex_state = 0, .external_lex_state = 7},
  [132] = {.lex_state = 0, .external_lex_state = 7},
  [133] = {.lex_state = 0, .external_lex_state = 7},
  [134] = {.lex_state = 0, .external_lex_state = 7},
  [135] = {.lex_state = 0, .external_lex_state = 7},
  [136] = {.lex_state = 0, .external_lex_state = 7},
  [137] = {.lex_state = 0, .external_lex_state = 7},
  [138] = {.lex_state = 0, .external_lex_state = 7},
  [139] = {.lex_state = 0, .external_lex_state = 7},
  [140] = {.lex_state = 0, .external_lex_state = 7},
  [141] = {.lex_state = 0, .external_lex_state = 7},
};

enum {
  ts_external_token__newline = 0,
  ts_external_token__blankline = 1,
  ts_external_token__overline = 2,
  ts_external_token__underline = 3,
  ts_external_token__char_bullet = 4,
  ts_external_token__numeric_bullet = 5,
  ts_external_token__text = 6,
  ts_external_token_emphasis = 7,
  ts_external_token_strong = 8,
  ts_external_token_interpreted_text = 9,
  ts_external_token_literal = 10,
  ts_external_token_substitution_reference = 11,
  ts_external_token__inline_target = 12,
  ts_external_token_footnote_reference = 13,
  ts_external_token_reference = 14,
  ts_external_token_standalone_hyperlink = 15,
  ts_external_token__explicit_markup_start = 16,
};

static TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__newline] = sym__newline,
  [ts_external_token__blankline] = sym__blankline,
  [ts_external_token__overline] = sym__overline,
  [ts_external_token__underline] = sym__underline,
  [ts_external_token__char_bullet] = sym__char_bullet,
  [ts_external_token__numeric_bullet] = sym__numeric_bullet,
  [ts_external_token__text] = sym__text,
  [ts_external_token_emphasis] = sym_emphasis,
  [ts_external_token_strong] = sym_strong,
  [ts_external_token_interpreted_text] = sym_interpreted_text,
  [ts_external_token_literal] = sym_literal,
  [ts_external_token_substitution_reference] = sym_substitution_reference,
  [ts_external_token__inline_target] = sym__inline_target,
  [ts_external_token_footnote_reference] = sym_footnote_reference,
  [ts_external_token_reference] = sym_reference,
  [ts_external_token_standalone_hyperlink] = sym_standalone_hyperlink,
  [ts_external_token__explicit_markup_start] = sym__explicit_markup_start,
};

static bool ts_external_scanner_states[12][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__newline] = true,
    [ts_external_token__blankline] = true,
    [ts_external_token__overline] = true,
    [ts_external_token__underline] = true,
    [ts_external_token__char_bullet] = true,
    [ts_external_token__numeric_bullet] = true,
    [ts_external_token__text] = true,
    [ts_external_token_emphasis] = true,
    [ts_external_token_strong] = true,
    [ts_external_token_interpreted_text] = true,
    [ts_external_token_literal] = true,
    [ts_external_token_substitution_reference] = true,
    [ts_external_token__inline_target] = true,
    [ts_external_token_footnote_reference] = true,
    [ts_external_token_reference] = true,
    [ts_external_token_standalone_hyperlink] = true,
    [ts_external_token__explicit_markup_start] = true,
  },
  [2] = {
    [ts_external_token__newline] = true,
    [ts_external_token__blankline] = true,
    [ts_external_token__overline] = true,
    [ts_external_token__char_bullet] = true,
    [ts_external_token__numeric_bullet] = true,
    [ts_external_token__text] = true,
    [ts_external_token_emphasis] = true,
    [ts_external_token_strong] = true,
    [ts_external_token_interpreted_text] = true,
    [ts_external_token_literal] = true,
    [ts_external_token_substitution_reference] = true,
    [ts_external_token__inline_target] = true,
    [ts_external_token_footnote_reference] = true,
    [ts_external_token_reference] = true,
    [ts_external_token_standalone_hyperlink] = true,
    [ts_external_token__explicit_markup_start] = true,
  },
  [3] = {
    [ts_external_token__newline] = true,
    [ts_external_token__text] = true,
    [ts_external_token_emphasis] = true,
    [ts_external_token_strong] = true,
    [ts_external_token_interpreted_text] = true,
    [ts_external_token_literal] = true,
    [ts_external_token_substitution_reference] = true,
    [ts_external_token__inline_target] = true,
    [ts_external_token_footnote_reference] = true,
    [ts_external_token_reference] = true,
    [ts_external_token_standalone_hyperlink] = true,
  },
  [4] = {
    [ts_external_token__newline] = true,
    [ts_external_token__blankline] = true,
    [ts_external_token__text] = true,
    [ts_external_token_emphasis] = true,
    [ts_external_token_strong] = true,
    [ts_external_token_interpreted_text] = true,
    [ts_external_token_literal] = true,
    [ts_external_token_substitution_reference] = true,
    [ts_external_token__inline_target] = true,
    [ts_external_token_footnote_reference] = true,
    [ts_external_token_reference] = true,
    [ts_external_token_standalone_hyperlink] = true,
  },
  [5] = {
    [ts_external_token__newline] = true,
    [ts_external_token__underline] = true,
    [ts_external_token__text] = true,
    [ts_external_token_emphasis] = true,
    [ts_external_token_strong] = true,
    [ts_external_token_interpreted_text] = true,
    [ts_external_token_literal] = true,
    [ts_external_token_substitution_reference] = true,
    [ts_external_token__inline_target] = true,
    [ts_external_token_footnote_reference] = true,
    [ts_external_token_reference] = true,
    [ts_external_token_standalone_hyperlink] = true,
  },
  [6] = {
    [ts_external_token__newline] = true,
    [ts_external_token__blankline] = true,
  },
  [7] = {
    [ts_external_token__newline] = true,
  },
  [8] = {
    [ts_external_token__newline] = true,
    [ts_external_token__explicit_markup_start] = true,
  },
  [9] = {
    [ts_external_token__newline] = true,
    [ts_external_token__char_bullet] = true,
  },
  [10] = {
    [ts_external_token__newline] = true,
    [ts_external_token__numeric_bullet] = true,
  },
  [11] = {
    [ts_external_token__newline] = true,
    [ts_external_token__underline] = true,
  },
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_] = ACTIONS(1),
    [anon_sym_TAB] = ACTIONS(1),
    [anon_sym_2] = ACTIONS(1),
    [anon_sym_3] = ACTIONS(1),
    [aux_sym_field_token2] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym__newline] = ACTIONS(3),
    [sym__blankline] = ACTIONS(1),
    [sym__overline] = ACTIONS(1),
    [sym__underline] = ACTIONS(1),
    [sym__char_bullet] = ACTIONS(1),
    [sym__numeric_bullet] = ACTIONS(1),
    [sym__text] = ACTIONS(1),
    [sym_emphasis] = ACTIONS(1),
    [sym_strong] = ACTIONS(1),
    [sym_interpreted_text] = ACTIONS(1),
    [sym_literal] = ACTIONS(1),
    [sym_substitution_reference] = ACTIONS(1),
    [sym__inline_target] = ACTIONS(1),
    [sym_footnote_reference] = ACTIONS(1),
    [sym_reference] = ACTIONS(1),
    [sym_standalone_hyperlink] = ACTIONS(1),
    [sym__explicit_markup_start] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(94),
    [sym_section] = STATE(3),
    [sym__body_elements] = STATE(3),
    [sym_paragraph] = STATE(98),
    [sym__list] = STATE(98),
    [sym_bullet_list] = STATE(98),
    [sym__bullet_list_item] = STATE(99),
    [sym_enumerated_list] = STATE(98),
    [sym__numeric_list_item] = STATE(128),
    [sym__markup_block] = STATE(98),
    [sym__footnote_block] = STATE(98),
    [sym_footnote] = STATE(127),
    [sym__citation_block] = STATE(98),
    [sym_citation] = STATE(84),
    [sym__hyperlink_target_block] = STATE(98),
    [sym_target] = STATE(125),
    [sym__anoynymous_hyperlink_target_block] = STATE(98),
    [sym__anonymous_target] = STATE(124),
    [sym__directive_block] = STATE(98),
    [sym_directive] = STATE(123),
    [sym__substitution_definition_block] = STATE(98),
    [sym_substitution_definition] = STATE(118),
    [sym__comment_block] = STATE(98),
    [sym_comment] = STATE(116),
    [aux_sym__line] = STATE(16),
    [sym__inline_markup] = STATE(37),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_paragraph_repeat1] = STATE(7),
    [aux_sym_bullet_list_repeat1] = STATE(61),
    [aux_sym_enumerated_list_repeat1] = STATE(63),
    [aux_sym__footnote_block_repeat1] = STATE(64),
    [aux_sym__citation_block_repeat1] = STATE(52),
    [aux_sym__hyperlink_target_block_repeat1] = STATE(67),
    [aux_sym__anoynymous_hyperlink_target_block_repeat1] = STATE(69),
    [aux_sym__directive_block_repeat1] = STATE(60),
    [aux_sym__substitution_definition_block_repeat1] = STATE(58),
    [aux_sym__comment_block_repeat1] = STATE(53),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym___] = ACTIONS(7),
    [aux_sym__line_token1] = ACTIONS(9),
    [sym__newline] = ACTIONS(3),
    [sym__blankline] = ACTIONS(11),
    [sym__overline] = ACTIONS(13),
    [sym__char_bullet] = ACTIONS(15),
    [sym__numeric_bullet] = ACTIONS(17),
    [sym__text] = ACTIONS(19),
    [sym_emphasis] = ACTIONS(19),
    [sym_strong] = ACTIONS(19),
    [sym_interpreted_text] = ACTIONS(19),
    [sym_literal] = ACTIONS(19),
    [sym_substitution_reference] = ACTIONS(19),
    [sym__inline_target] = ACTIONS(19),
    [sym_footnote_reference] = ACTIONS(19),
    [sym_reference] = ACTIONS(19),
    [sym_standalone_hyperlink] = ACTIONS(19),
    [sym__explicit_markup_start] = ACTIONS(21),
  },
  [2] = {
    [sym_section] = STATE(2),
    [sym__body_elements] = STATE(2),
    [sym_paragraph] = STATE(98),
    [sym__list] = STATE(98),
    [sym_bullet_list] = STATE(98),
    [sym__bullet_list_item] = STATE(99),
    [sym_enumerated_list] = STATE(98),
    [sym__numeric_list_item] = STATE(128),
    [sym__markup_block] = STATE(98),
    [sym__footnote_block] = STATE(98),
    [sym_footnote] = STATE(127),
    [sym__citation_block] = STATE(98),
    [sym_citation] = STATE(84),
    [sym__hyperlink_target_block] = STATE(98),
    [sym_target] = STATE(125),
    [sym__anoynymous_hyperlink_target_block] = STATE(98),
    [sym__anonymous_target] = STATE(124),
    [sym__directive_block] = STATE(98),
    [sym_directive] = STATE(123),
    [sym__substitution_definition_block] = STATE(98),
    [sym_substitution_definition] = STATE(118),
    [sym__comment_block] = STATE(98),
    [sym_comment] = STATE(116),
    [aux_sym__line] = STATE(16),
    [sym__inline_markup] = STATE(37),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_paragraph_repeat1] = STATE(7),
    [aux_sym_bullet_list_repeat1] = STATE(61),
    [aux_sym_enumerated_list_repeat1] = STATE(63),
    [aux_sym__footnote_block_repeat1] = STATE(64),
    [aux_sym__citation_block_repeat1] = STATE(52),
    [aux_sym__hyperlink_target_block_repeat1] = STATE(67),
    [aux_sym__anoynymous_hyperlink_target_block_repeat1] = STATE(69),
    [aux_sym__directive_block_repeat1] = STATE(60),
    [aux_sym__substitution_definition_block_repeat1] = STATE(58),
    [aux_sym__comment_block_repeat1] = STATE(53),
    [ts_builtin_sym_end] = ACTIONS(23),
    [anon_sym___] = ACTIONS(25),
    [aux_sym__line_token1] = ACTIONS(28),
    [sym__newline] = ACTIONS(3),
    [sym__blankline] = ACTIONS(31),
    [sym__overline] = ACTIONS(34),
    [sym__char_bullet] = ACTIONS(37),
    [sym__numeric_bullet] = ACTIONS(40),
    [sym__text] = ACTIONS(43),
    [sym_emphasis] = ACTIONS(43),
    [sym_strong] = ACTIONS(43),
    [sym_interpreted_text] = ACTIONS(43),
    [sym_literal] = ACTIONS(43),
    [sym_substitution_reference] = ACTIONS(43),
    [sym__inline_target] = ACTIONS(43),
    [sym_footnote_reference] = ACTIONS(43),
    [sym_reference] = ACTIONS(43),
    [sym_standalone_hyperlink] = ACTIONS(43),
    [sym__explicit_markup_start] = ACTIONS(46),
  },
  [3] = {
    [sym_section] = STATE(2),
    [sym__body_elements] = STATE(2),
    [sym_paragraph] = STATE(98),
    [sym__list] = STATE(98),
    [sym_bullet_list] = STATE(98),
    [sym__bullet_list_item] = STATE(99),
    [sym_enumerated_list] = STATE(98),
    [sym__numeric_list_item] = STATE(128),
    [sym__markup_block] = STATE(98),
    [sym__footnote_block] = STATE(98),
    [sym_footnote] = STATE(127),
    [sym__citation_block] = STATE(98),
    [sym_citation] = STATE(84),
    [sym__hyperlink_target_block] = STATE(98),
    [sym_target] = STATE(125),
    [sym__anoynymous_hyperlink_target_block] = STATE(98),
    [sym__anonymous_target] = STATE(124),
    [sym__directive_block] = STATE(98),
    [sym_directive] = STATE(123),
    [sym__substitution_definition_block] = STATE(98),
    [sym_substitution_definition] = STATE(118),
    [sym__comment_block] = STATE(98),
    [sym_comment] = STATE(116),
    [aux_sym__line] = STATE(16),
    [sym__inline_markup] = STATE(37),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_paragraph_repeat1] = STATE(7),
    [aux_sym_bullet_list_repeat1] = STATE(61),
    [aux_sym_enumerated_list_repeat1] = STATE(63),
    [aux_sym__footnote_block_repeat1] = STATE(64),
    [aux_sym__citation_block_repeat1] = STATE(52),
    [aux_sym__hyperlink_target_block_repeat1] = STATE(67),
    [aux_sym__anoynymous_hyperlink_target_block_repeat1] = STATE(69),
    [aux_sym__directive_block_repeat1] = STATE(60),
    [aux_sym__substitution_definition_block_repeat1] = STATE(58),
    [aux_sym__comment_block_repeat1] = STATE(53),
    [ts_builtin_sym_end] = ACTIONS(49),
    [anon_sym___] = ACTIONS(7),
    [aux_sym__line_token1] = ACTIONS(9),
    [sym__newline] = ACTIONS(3),
    [sym__blankline] = ACTIONS(51),
    [sym__overline] = ACTIONS(13),
    [sym__char_bullet] = ACTIONS(15),
    [sym__numeric_bullet] = ACTIONS(17),
    [sym__text] = ACTIONS(19),
    [sym_emphasis] = ACTIONS(19),
    [sym_strong] = ACTIONS(19),
    [sym_interpreted_text] = ACTIONS(19),
    [sym_literal] = ACTIONS(19),
    [sym_substitution_reference] = ACTIONS(19),
    [sym__inline_target] = ACTIONS(19),
    [sym_footnote_reference] = ACTIONS(19),
    [sym_reference] = ACTIONS(19),
    [sym_standalone_hyperlink] = ACTIONS(19),
    [sym__explicit_markup_start] = ACTIONS(21),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(55), 1,
      aux_sym__line_token1,
    ACTIONS(53), 17,
      sym__blankline,
      sym__overline,
      sym__char_bullet,
      sym__numeric_bullet,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      sym__explicit_markup_start,
      ts_builtin_sym_end,
      anon_sym___,
  [26] = 3,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(59), 1,
      aux_sym__line_token1,
    ACTIONS(57), 17,
      sym__blankline,
      sym__overline,
      sym__char_bullet,
      sym__numeric_bullet,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      sym__explicit_markup_start,
      ts_builtin_sym_end,
      anon_sym___,
  [52] = 3,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(63), 1,
      aux_sym__line_token1,
    ACTIONS(61), 17,
      sym__blankline,
      sym__overline,
      sym__char_bullet,
      sym__numeric_bullet,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      sym__explicit_markup_start,
      ts_builtin_sym_end,
      anon_sym___,
  [78] = 5,
    ACTIONS(3), 1,
      sym__newline,
    STATE(8), 1,
      aux_sym_paragraph_repeat1,
    STATE(9), 1,
      aux_sym__line,
    STATE(37), 1,
      sym__inline_markup,
    ACTIONS(19), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [104] = 5,
    ACTIONS(3), 1,
      sym__newline,
    STATE(8), 1,
      aux_sym_paragraph_repeat1,
    STATE(28), 1,
      aux_sym__line,
    STATE(38), 1,
      sym__inline_markup,
    ACTIONS(65), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [130] = 5,
    ACTIONS(68), 1,
      sym__newline,
    ACTIONS(70), 1,
      sym__blankline,
    STATE(10), 1,
      aux_sym__line,
    STATE(37), 1,
      sym__inline_markup,
    ACTIONS(19), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [156] = 4,
    STATE(10), 1,
      aux_sym__line,
    STATE(37), 1,
      sym__inline_markup,
    ACTIONS(75), 2,
      sym__newline,
      sym__blankline,
    ACTIONS(72), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [180] = 4,
    STATE(10), 1,
      aux_sym__line,
    STATE(37), 1,
      sym__inline_markup,
    ACTIONS(77), 2,
      sym__newline,
      sym__blankline,
    ACTIONS(19), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [204] = 4,
    STATE(10), 1,
      aux_sym__line,
    STATE(37), 1,
      sym__inline_markup,
    ACTIONS(79), 2,
      sym__newline,
      sym__blankline,
    ACTIONS(19), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [228] = 4,
    STATE(10), 1,
      aux_sym__line,
    STATE(37), 1,
      sym__inline_markup,
    ACTIONS(81), 2,
      sym__newline,
      sym__blankline,
    ACTIONS(19), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [252] = 4,
    STATE(10), 1,
      aux_sym__line,
    STATE(37), 1,
      sym__inline_markup,
    ACTIONS(83), 2,
      sym__newline,
      sym__blankline,
    ACTIONS(19), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [276] = 4,
    STATE(10), 1,
      aux_sym__line,
    STATE(37), 1,
      sym__inline_markup,
    ACTIONS(85), 2,
      sym__newline,
      sym__blankline,
    ACTIONS(19), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [300] = 5,
    ACTIONS(87), 1,
      sym__newline,
    ACTIONS(89), 1,
      sym__blankline,
    STATE(10), 1,
      aux_sym__line,
    STATE(37), 1,
      sym__inline_markup,
    ACTIONS(19), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [326] = 4,
    ACTIONS(3), 1,
      sym__newline,
    STATE(18), 1,
      aux_sym__line,
    STATE(38), 1,
      sym__inline_markup,
    ACTIONS(91), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [349] = 4,
    ACTIONS(79), 1,
      sym__newline,
    STATE(20), 1,
      aux_sym__line,
    STATE(38), 1,
      sym__inline_markup,
    ACTIONS(91), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [372] = 4,
    ACTIONS(85), 1,
      sym__newline,
    STATE(20), 1,
      aux_sym__line,
    STATE(38), 1,
      sym__inline_markup,
    ACTIONS(91), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [395] = 4,
    ACTIONS(75), 1,
      sym__newline,
    STATE(20), 1,
      aux_sym__line,
    STATE(38), 1,
      sym__inline_markup,
    ACTIONS(93), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [418] = 4,
    ACTIONS(83), 1,
      sym__newline,
    STATE(20), 1,
      aux_sym__line,
    STATE(38), 1,
      sym__inline_markup,
    ACTIONS(91), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [441] = 4,
    ACTIONS(3), 1,
      sym__newline,
    STATE(19), 1,
      aux_sym__line,
    STATE(38), 1,
      sym__inline_markup,
    ACTIONS(91), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [464] = 4,
    ACTIONS(3), 1,
      sym__newline,
    STATE(21), 1,
      aux_sym__line,
    STATE(38), 1,
      sym__inline_markup,
    ACTIONS(91), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [487] = 4,
    ACTIONS(3), 1,
      sym__newline,
    STATE(27), 1,
      aux_sym__line,
    STATE(38), 1,
      sym__inline_markup,
    ACTIONS(91), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [510] = 4,
    ACTIONS(3), 1,
      sym__newline,
    STATE(35), 1,
      aux_sym__line,
    STATE(38), 1,
      sym__inline_markup,
    ACTIONS(91), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [533] = 4,
    ACTIONS(3), 1,
      sym__newline,
    STATE(29), 1,
      aux_sym__line,
    STATE(38), 1,
      sym__inline_markup,
    ACTIONS(91), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [556] = 4,
    ACTIONS(81), 1,
      sym__newline,
    STATE(20), 1,
      aux_sym__line,
    STATE(38), 1,
      sym__inline_markup,
    ACTIONS(91), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [579] = 4,
    ACTIONS(68), 1,
      sym__newline,
    STATE(20), 1,
      aux_sym__line,
    STATE(38), 1,
      sym__inline_markup,
    ACTIONS(91), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [602] = 4,
    ACTIONS(96), 1,
      sym__newline,
    STATE(20), 1,
      aux_sym__line,
    STATE(38), 1,
      sym__inline_markup,
    ACTIONS(91), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [625] = 4,
    ACTIONS(3), 1,
      sym__newline,
    STATE(11), 1,
      aux_sym__line,
    STATE(37), 1,
      sym__inline_markup,
    ACTIONS(19), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [648] = 4,
    ACTIONS(3), 1,
      sym__newline,
    STATE(12), 1,
      aux_sym__line,
    STATE(37), 1,
      sym__inline_markup,
    ACTIONS(19), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [671] = 4,
    ACTIONS(3), 1,
      sym__newline,
    STATE(13), 1,
      aux_sym__line,
    STATE(37), 1,
      sym__inline_markup,
    ACTIONS(19), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [694] = 4,
    ACTIONS(3), 1,
      sym__newline,
    STATE(14), 1,
      aux_sym__line,
    STATE(37), 1,
      sym__inline_markup,
    ACTIONS(19), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [717] = 4,
    ACTIONS(3), 1,
      sym__newline,
    STATE(15), 1,
      aux_sym__line,
    STATE(37), 1,
      sym__inline_markup,
    ACTIONS(19), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [740] = 4,
    ACTIONS(77), 1,
      sym__newline,
    STATE(20), 1,
      aux_sym__line,
    STATE(38), 1,
      sym__inline_markup,
    ACTIONS(91), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [763] = 3,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(100), 1,
      sym__underline,
    ACTIONS(98), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [783] = 1,
    ACTIONS(102), 13,
      sym__newline,
      sym__blankline,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [799] = 1,
    ACTIONS(102), 12,
      sym__newline,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [814] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(98), 11,
      sym__text,
      sym_emphasis,
      sym_strong,
      sym_interpreted_text,
      sym_literal,
      sym_substitution_reference,
      sym__inline_target,
      sym_footnote_reference,
      sym_reference,
      sym_standalone_hyperlink,
      aux_sym__line_token1,
  [831] = 7,
    ACTIONS(106), 1,
      aux_sym_footnote_token1,
    ACTIONS(108), 1,
      aux_sym_citation_token1,
    ACTIONS(110), 1,
      aux_sym_target_token1,
    ACTIONS(112), 1,
      aux_sym_directive_token1,
    ACTIONS(114), 1,
      aux_sym_substitution_definition_token1,
    ACTIONS(116), 2,
      sym__newline,
      sym__blankline,
    ACTIONS(104), 4,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_2,
      anon_sym_3,
  [857] = 2,
    ACTIONS(120), 2,
      sym__newline,
      sym__blankline,
    ACTIONS(118), 4,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_2,
      anon_sym_3,
  [868] = 2,
    ACTIONS(116), 2,
      sym__newline,
      sym__blankline,
    ACTIONS(122), 4,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_2,
      anon_sym_3,
  [879] = 2,
    ACTIONS(116), 1,
      sym__newline,
    ACTIONS(124), 4,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_2,
      anon_sym_3,
  [889] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(126), 4,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_2,
      anon_sym_3,
  [899] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(128), 4,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_2,
      anon_sym_3,
  [909] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(130), 4,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_2,
      anon_sym_3,
  [919] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(132), 4,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_2,
      anon_sym_3,
  [929] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(134), 4,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_2,
      anon_sym_3,
  [939] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(136), 4,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_2,
      anon_sym_3,
  [949] = 2,
    ACTIONS(120), 1,
      sym__newline,
    ACTIONS(138), 4,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_2,
      anon_sym_3,
  [959] = 3,
    ACTIONS(140), 1,
      aux_sym_field_token2,
    STATE(51), 1,
      aux_sym_field_repeat1,
    ACTIONS(143), 2,
      sym__newline,
      sym__blankline,
  [970] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(145), 1,
      sym__explicit_markup_start,
    STATE(65), 1,
      aux_sym__citation_block_repeat1,
    STATE(113), 1,
      sym_citation,
  [983] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(147), 1,
      sym__explicit_markup_start,
    STATE(54), 1,
      aux_sym__comment_block_repeat1,
    STATE(104), 1,
      sym_comment,
  [996] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(149), 1,
      sym__explicit_markup_start,
    STATE(54), 1,
      aux_sym__comment_block_repeat1,
    STATE(133), 1,
      sym_comment,
  [1009] = 3,
    ACTIONS(152), 1,
      aux_sym_field_token2,
    STATE(51), 1,
      aux_sym_field_repeat1,
    ACTIONS(154), 2,
      sym__newline,
      sym__blankline,
  [1020] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(156), 1,
      sym__explicit_markup_start,
    STATE(56), 1,
      aux_sym__substitution_definition_block_repeat1,
    STATE(134), 1,
      sym_substitution_definition,
  [1033] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(159), 1,
      sym__char_bullet,
    STATE(57), 1,
      aux_sym_bullet_list_repeat1,
    STATE(141), 1,
      sym__bullet_list_item,
  [1046] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(162), 1,
      sym__explicit_markup_start,
    STATE(56), 1,
      aux_sym__substitution_definition_block_repeat1,
    STATE(105), 1,
      sym_substitution_definition,
  [1059] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(164), 1,
      sym__numeric_bullet,
    STATE(59), 1,
      aux_sym_enumerated_list_repeat1,
    STATE(140), 1,
      sym__numeric_list_item,
  [1072] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(167), 1,
      sym__explicit_markup_start,
    STATE(66), 1,
      aux_sym__directive_block_repeat1,
    STATE(107), 1,
      sym_directive,
  [1085] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(15), 1,
      sym__char_bullet,
    STATE(57), 1,
      aux_sym_bullet_list_repeat1,
    STATE(100), 1,
      sym__bullet_list_item,
  [1098] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(169), 1,
      sym__explicit_markup_start,
    STATE(62), 1,
      aux_sym__footnote_block_repeat1,
    STATE(139), 1,
      sym_footnote,
  [1111] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(17), 1,
      sym__numeric_bullet,
    STATE(59), 1,
      aux_sym_enumerated_list_repeat1,
    STATE(101), 1,
      sym__numeric_list_item,
  [1124] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(172), 1,
      sym__explicit_markup_start,
    STATE(62), 1,
      aux_sym__footnote_block_repeat1,
    STATE(129), 1,
      sym_footnote,
  [1137] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(174), 1,
      sym__explicit_markup_start,
    STATE(65), 1,
      aux_sym__citation_block_repeat1,
    STATE(138), 1,
      sym_citation,
  [1150] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(177), 1,
      sym__explicit_markup_start,
    STATE(66), 1,
      aux_sym__directive_block_repeat1,
    STATE(135), 1,
      sym_directive,
  [1163] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(180), 1,
      sym__explicit_markup_start,
    STATE(68), 1,
      aux_sym__hyperlink_target_block_repeat1,
    STATE(111), 1,
      sym_target,
  [1176] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(182), 1,
      sym__explicit_markup_start,
    STATE(68), 1,
      aux_sym__hyperlink_target_block_repeat1,
    STATE(137), 1,
      sym_target,
  [1189] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(7), 1,
      anon_sym___,
    STATE(70), 1,
      aux_sym__anoynymous_hyperlink_target_block_repeat1,
    STATE(110), 1,
      sym__anonymous_target,
  [1202] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(185), 1,
      anon_sym___,
    STATE(70), 1,
      aux_sym__anoynymous_hyperlink_target_block_repeat1,
    STATE(136), 1,
      sym__anonymous_target,
  [1215] = 3,
    ACTIONS(152), 1,
      aux_sym_field_token2,
    STATE(51), 1,
      aux_sym_field_repeat1,
    ACTIONS(188), 2,
      sym__newline,
      sym__blankline,
  [1226] = 3,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(190), 1,
      aux_sym_field_token2,
    STATE(71), 1,
      aux_sym_field_repeat1,
  [1236] = 3,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(192), 1,
      aux_sym__embed_directive_token1,
    STATE(91), 1,
      sym__embed_directive,
  [1246] = 3,
    ACTIONS(154), 1,
      sym__newline,
    ACTIONS(194), 1,
      aux_sym_field_token2,
    STATE(75), 1,
      aux_sym_field_repeat1,
  [1256] = 3,
    ACTIONS(143), 1,
      sym__newline,
    ACTIONS(196), 1,
      aux_sym_field_token2,
    STATE(75), 1,
      aux_sym_field_repeat1,
  [1266] = 3,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(199), 1,
      aux_sym_field_token2,
    STATE(78), 1,
      aux_sym_field_repeat1,
  [1276] = 2,
    ACTIONS(201), 1,
      aux_sym_target_token2,
    ACTIONS(203), 2,
      sym__newline,
      sym__blankline,
  [1284] = 3,
    ACTIONS(188), 1,
      sym__newline,
    ACTIONS(194), 1,
      aux_sym_field_token2,
    STATE(75), 1,
      aux_sym_field_repeat1,
  [1294] = 3,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(205), 1,
      aux_sym__embed_directive_token1,
    STATE(130), 1,
      sym__embed_directive,
  [1304] = 3,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(207), 1,
      aux_sym_field_token2,
    STATE(74), 1,
      aux_sym_field_repeat1,
  [1314] = 3,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(209), 1,
      aux_sym_field_token2,
    STATE(55), 1,
      aux_sym_field_repeat1,
  [1324] = 2,
    ACTIONS(211), 1,
      aux_sym_target_token2,
    ACTIONS(213), 2,
      sym__newline,
      sym__blankline,
  [1332] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(215), 1,
      aux_sym_footnote_token1,
  [1339] = 2,
    ACTIONS(217), 1,
      sym__newline,
    ACTIONS(219), 1,
      sym__blankline,
  [1346] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(221), 1,
      sym__explicit_markup_start,
  [1353] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(223), 1,
      sym__explicit_markup_start,
  [1360] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(225), 1,
      sym__numeric_bullet,
  [1367] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(227), 1,
      sym__char_bullet,
  [1374] = 1,
    ACTIONS(229), 2,
      sym__newline,
      sym__blankline,
  [1379] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(231), 1,
      anon_sym_COLON_COLON,
  [1386] = 1,
    ACTIONS(233), 2,
      sym__newline,
      sym__blankline,
  [1391] = 1,
    ACTIONS(235), 2,
      sym__newline,
      sym__blankline,
  [1396] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(237), 1,
      anon_sym_COLON_COLON,
  [1403] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(239), 1,
      ts_builtin_sym_end,
  [1410] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(241), 1,
      sym__explicit_markup_start,
  [1417] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(243), 1,
      aux_sym_substitution_definition_token1,
  [1424] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(245), 1,
      sym__explicit_markup_start,
  [1431] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(247), 1,
      sym__blankline,
  [1438] = 2,
    ACTIONS(249), 1,
      sym__newline,
    ACTIONS(251), 1,
      sym__blankline,
  [1445] = 2,
    ACTIONS(249), 1,
      sym__newline,
    ACTIONS(253), 1,
      sym__blankline,
  [1452] = 2,
    ACTIONS(255), 1,
      sym__newline,
    ACTIONS(257), 1,
      sym__blankline,
  [1459] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(259), 1,
      sym__explicit_markup_start,
  [1466] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(261), 1,
      sym__underline,
  [1473] = 2,
    ACTIONS(263), 1,
      sym__newline,
    ACTIONS(265), 1,
      sym__blankline,
  [1480] = 2,
    ACTIONS(267), 1,
      sym__newline,
    ACTIONS(269), 1,
      sym__blankline,
  [1487] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(114), 1,
      aux_sym_substitution_definition_token1,
  [1494] = 2,
    ACTIONS(271), 1,
      sym__newline,
    ACTIONS(273), 1,
      sym__blankline,
  [1501] = 2,
    ACTIONS(203), 1,
      sym__newline,
    ACTIONS(275), 1,
      aux_sym_target_token2,
  [1508] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(112), 1,
      aux_sym_directive_token1,
  [1515] = 2,
    ACTIONS(277), 1,
      sym__newline,
    ACTIONS(279), 1,
      sym__blankline,
  [1522] = 2,
    ACTIONS(281), 1,
      sym__newline,
    ACTIONS(283), 1,
      sym__blankline,
  [1529] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(110), 1,
      aux_sym_target_token1,
  [1536] = 2,
    ACTIONS(217), 1,
      sym__newline,
    ACTIONS(285), 1,
      sym__blankline,
  [1543] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(287), 1,
      aux_sym_citation_token1,
  [1550] = 2,
    ACTIONS(213), 1,
      sym__newline,
    ACTIONS(289), 1,
      aux_sym_target_token2,
  [1557] = 2,
    ACTIONS(263), 1,
      sym__newline,
    ACTIONS(291), 1,
      sym__blankline,
  [1564] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(106), 1,
      aux_sym_footnote_token1,
  [1571] = 2,
    ACTIONS(267), 1,
      sym__newline,
    ACTIONS(293), 1,
      sym__blankline,
  [1578] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(295), 1,
      anon_sym___,
  [1585] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(297), 1,
      aux_sym_citation_token1,
  [1592] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(299), 1,
      aux_sym_target_token1,
  [1599] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(301), 1,
      aux_sym_directive_token1,
  [1606] = 2,
    ACTIONS(271), 1,
      sym__newline,
    ACTIONS(303), 1,
      sym__blankline,
  [1613] = 2,
    ACTIONS(277), 1,
      sym__newline,
    ACTIONS(305), 1,
      sym__blankline,
  [1620] = 2,
    ACTIONS(281), 1,
      sym__newline,
    ACTIONS(307), 1,
      sym__blankline,
  [1627] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(309), 1,
      sym__explicit_markup_start,
  [1634] = 2,
    ACTIONS(311), 1,
      sym__newline,
    ACTIONS(313), 1,
      sym__blankline,
  [1641] = 2,
    ACTIONS(255), 1,
      sym__newline,
    ACTIONS(315), 1,
      sym__blankline,
  [1648] = 2,
    ACTIONS(311), 1,
      sym__newline,
    ACTIONS(317), 1,
      sym__blankline,
  [1655] = 1,
    ACTIONS(233), 1,
      sym__newline,
  [1659] = 1,
    ACTIONS(229), 1,
      sym__newline,
  [1663] = 1,
    ACTIONS(235), 1,
      sym__newline,
  [1667] = 1,
    ACTIONS(263), 1,
      sym__newline,
  [1671] = 1,
    ACTIONS(267), 1,
      sym__newline,
  [1675] = 1,
    ACTIONS(271), 1,
      sym__newline,
  [1679] = 1,
    ACTIONS(277), 1,
      sym__newline,
  [1683] = 1,
    ACTIONS(281), 1,
      sym__newline,
  [1687] = 1,
    ACTIONS(217), 1,
      sym__newline,
  [1691] = 1,
    ACTIONS(311), 1,
      sym__newline,
  [1695] = 1,
    ACTIONS(255), 1,
      sym__newline,
  [1699] = 1,
    ACTIONS(249), 1,
      sym__newline,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 26,
  [SMALL_STATE(6)] = 52,
  [SMALL_STATE(7)] = 78,
  [SMALL_STATE(8)] = 104,
  [SMALL_STATE(9)] = 130,
  [SMALL_STATE(10)] = 156,
  [SMALL_STATE(11)] = 180,
  [SMALL_STATE(12)] = 204,
  [SMALL_STATE(13)] = 228,
  [SMALL_STATE(14)] = 252,
  [SMALL_STATE(15)] = 276,
  [SMALL_STATE(16)] = 300,
  [SMALL_STATE(17)] = 326,
  [SMALL_STATE(18)] = 349,
  [SMALL_STATE(19)] = 372,
  [SMALL_STATE(20)] = 395,
  [SMALL_STATE(21)] = 418,
  [SMALL_STATE(22)] = 441,
  [SMALL_STATE(23)] = 464,
  [SMALL_STATE(24)] = 487,
  [SMALL_STATE(25)] = 510,
  [SMALL_STATE(26)] = 533,
  [SMALL_STATE(27)] = 556,
  [SMALL_STATE(28)] = 579,
  [SMALL_STATE(29)] = 602,
  [SMALL_STATE(30)] = 625,
  [SMALL_STATE(31)] = 648,
  [SMALL_STATE(32)] = 671,
  [SMALL_STATE(33)] = 694,
  [SMALL_STATE(34)] = 717,
  [SMALL_STATE(35)] = 740,
  [SMALL_STATE(36)] = 763,
  [SMALL_STATE(37)] = 783,
  [SMALL_STATE(38)] = 799,
  [SMALL_STATE(39)] = 814,
  [SMALL_STATE(40)] = 831,
  [SMALL_STATE(41)] = 857,
  [SMALL_STATE(42)] = 868,
  [SMALL_STATE(43)] = 879,
  [SMALL_STATE(44)] = 889,
  [SMALL_STATE(45)] = 899,
  [SMALL_STATE(46)] = 909,
  [SMALL_STATE(47)] = 919,
  [SMALL_STATE(48)] = 929,
  [SMALL_STATE(49)] = 939,
  [SMALL_STATE(50)] = 949,
  [SMALL_STATE(51)] = 959,
  [SMALL_STATE(52)] = 970,
  [SMALL_STATE(53)] = 983,
  [SMALL_STATE(54)] = 996,
  [SMALL_STATE(55)] = 1009,
  [SMALL_STATE(56)] = 1020,
  [SMALL_STATE(57)] = 1033,
  [SMALL_STATE(58)] = 1046,
  [SMALL_STATE(59)] = 1059,
  [SMALL_STATE(60)] = 1072,
  [SMALL_STATE(61)] = 1085,
  [SMALL_STATE(62)] = 1098,
  [SMALL_STATE(63)] = 1111,
  [SMALL_STATE(64)] = 1124,
  [SMALL_STATE(65)] = 1137,
  [SMALL_STATE(66)] = 1150,
  [SMALL_STATE(67)] = 1163,
  [SMALL_STATE(68)] = 1176,
  [SMALL_STATE(69)] = 1189,
  [SMALL_STATE(70)] = 1202,
  [SMALL_STATE(71)] = 1215,
  [SMALL_STATE(72)] = 1226,
  [SMALL_STATE(73)] = 1236,
  [SMALL_STATE(74)] = 1246,
  [SMALL_STATE(75)] = 1256,
  [SMALL_STATE(76)] = 1266,
  [SMALL_STATE(77)] = 1276,
  [SMALL_STATE(78)] = 1284,
  [SMALL_STATE(79)] = 1294,
  [SMALL_STATE(80)] = 1304,
  [SMALL_STATE(81)] = 1314,
  [SMALL_STATE(82)] = 1324,
  [SMALL_STATE(83)] = 1332,
  [SMALL_STATE(84)] = 1339,
  [SMALL_STATE(85)] = 1346,
  [SMALL_STATE(86)] = 1353,
  [SMALL_STATE(87)] = 1360,
  [SMALL_STATE(88)] = 1367,
  [SMALL_STATE(89)] = 1374,
  [SMALL_STATE(90)] = 1379,
  [SMALL_STATE(91)] = 1386,
  [SMALL_STATE(92)] = 1391,
  [SMALL_STATE(93)] = 1396,
  [SMALL_STATE(94)] = 1403,
  [SMALL_STATE(95)] = 1410,
  [SMALL_STATE(96)] = 1417,
  [SMALL_STATE(97)] = 1424,
  [SMALL_STATE(98)] = 1431,
  [SMALL_STATE(99)] = 1438,
  [SMALL_STATE(100)] = 1445,
  [SMALL_STATE(101)] = 1452,
  [SMALL_STATE(102)] = 1459,
  [SMALL_STATE(103)] = 1466,
  [SMALL_STATE(104)] = 1473,
  [SMALL_STATE(105)] = 1480,
  [SMALL_STATE(106)] = 1487,
  [SMALL_STATE(107)] = 1494,
  [SMALL_STATE(108)] = 1501,
  [SMALL_STATE(109)] = 1508,
  [SMALL_STATE(110)] = 1515,
  [SMALL_STATE(111)] = 1522,
  [SMALL_STATE(112)] = 1529,
  [SMALL_STATE(113)] = 1536,
  [SMALL_STATE(114)] = 1543,
  [SMALL_STATE(115)] = 1550,
  [SMALL_STATE(116)] = 1557,
  [SMALL_STATE(117)] = 1564,
  [SMALL_STATE(118)] = 1571,
  [SMALL_STATE(119)] = 1578,
  [SMALL_STATE(120)] = 1585,
  [SMALL_STATE(121)] = 1592,
  [SMALL_STATE(122)] = 1599,
  [SMALL_STATE(123)] = 1606,
  [SMALL_STATE(124)] = 1613,
  [SMALL_STATE(125)] = 1620,
  [SMALL_STATE(126)] = 1627,
  [SMALL_STATE(127)] = 1634,
  [SMALL_STATE(128)] = 1641,
  [SMALL_STATE(129)] = 1648,
  [SMALL_STATE(130)] = 1655,
  [SMALL_STATE(131)] = 1659,
  [SMALL_STATE(132)] = 1663,
  [SMALL_STATE(133)] = 1667,
  [SMALL_STATE(134)] = 1671,
  [SMALL_STATE(135)] = 1675,
  [SMALL_STATE(136)] = 1679,
  [SMALL_STATE(137)] = 1683,
  [SMALL_STATE(138)] = 1687,
  [SMALL_STATE(139)] = 1691,
  [SMALL_STATE(140)] = 1695,
  [SMALL_STATE(141)] = 1699,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(77),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(37),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(2),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(26),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(46),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(45),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(37),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(40),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__body_elements, 2),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__body_elements, 2),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 3, .production_id = 1),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section, 3, .production_id = 1),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 4, .production_id = 2),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section, 4, .production_id = 2),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(38),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 2),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__line, 2), SHIFT_REPEAT(37),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__line, 2),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__bullet_list_item, 3),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__numeric_list_item, 3),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_footnote, 3),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_citation, 3),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 1),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__line, 2), SHIFT_REPEAT(38),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__line, 1),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 2),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [140] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_field_repeat1, 2), SHIFT_REPEAT(51),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_field_repeat1, 2),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [149] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__comment_block_repeat1, 2), SHIFT_REPEAT(43),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 4),
  [156] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__substitution_definition_block_repeat1, 2), SHIFT_REPEAT(96),
  [159] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bullet_list_repeat1, 2), SHIFT_REPEAT(49),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [164] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enumerated_list_repeat1, 2), SHIFT_REPEAT(47),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [169] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__footnote_block_repeat1, 2), SHIFT_REPEAT(83),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [174] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__citation_block_repeat1, 2), SHIFT_REPEAT(120),
  [177] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__directive_block_repeat1, 2), SHIFT_REPEAT(122),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [182] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__hyperlink_target_block_repeat1, 2), SHIFT_REPEAT(121),
  [185] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__anoynymous_hyperlink_target_block_repeat1, 2), SHIFT_REPEAT(108),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__embed_directive, 4),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [196] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_field_repeat1, 2), SHIFT_REPEAT(75),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__anonymous_target, 1),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target, 2),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__citation_block, 1),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__citation_block_repeat1, 2),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__footnote_block_repeat1, 2),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enumerated_list_repeat1, 2),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_bullet_list_repeat1, 2),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target, 3),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_substitution_definition, 3),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__anonymous_target, 2),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [239] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__substitution_definition_block_repeat1, 2),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__comment_block_repeat1, 2),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bullet_list, 1),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bullet_list, 2),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enumerated_list, 2),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__directive_block_repeat1, 2),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__comment_block, 2),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__substitution_definition_block, 2),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__directive_block, 2),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__anoynymous_hyperlink_target_block, 2),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__hyperlink_target_block, 2),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__citation_block, 2),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__comment_block, 1),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__substitution_definition_block, 1),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__anoynymous_hyperlink_target_block_repeat1, 2),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [303] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__directive_block, 1),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__anoynymous_hyperlink_target_block, 1),
  [307] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__hyperlink_target_block, 1),
  [309] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__hyperlink_target_block_repeat1, 2),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [313] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__footnote_block, 1),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enumerated_list, 1),
  [317] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__footnote_block, 2),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_rst_external_scanner_create(void);
void tree_sitter_rst_external_scanner_destroy(void *);
bool tree_sitter_rst_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_rst_external_scanner_serialize(void *, char *);
void tree_sitter_rst_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_rst(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const unsigned short *)ts_parse_table,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .symbol_names = ts_symbol_names,
    .public_symbol_map = ts_symbol_map,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .external_scanner = {
      (const bool *)ts_external_scanner_states,
      ts_external_scanner_symbol_map,
      tree_sitter_rst_external_scanner_create,
      tree_sitter_rst_external_scanner_destroy,
      tree_sitter_rst_external_scanner_scan,
      tree_sitter_rst_external_scanner_serialize,
      tree_sitter_rst_external_scanner_deserialize,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
