name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TS: "node_modules/.bin/tree-sitter"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: make all test
      - run: make parse-examples
  windows:
    runs-on: windows-latest
    env:
      TS: "node_modules/.bin/tree-sitter"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run build
      - run: npm run test
  mac:
    runs-on: macos-latest
    env:
      TS: "node_modules/.bin/tree-sitter"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run build
      - run: npm run test
